// template: { name: "", role: "", img: "img-japan/", school: "", bonds: [] },
const characters = [
    { name: "Hinata SP",      role: "MB", img: "img-japan/hinataSP.png",      power:["Quick","Receive"],         school: "Karasuno",      bonds: ["The Absolute King VS the Freak Duo SP","Similar Builds","Weird Duo (Hanami)","Hanami","Number One Disciple SP","Karasuno's Red Mark Squad (Hanami ver.)","Sun vs Moon","Strange Friendship"] },
    { name: "Hinata SSR",     role: "MB", img: "img-japan/hinataSSR.png",     power:"Quick",                     school: "Karasuno",      bonds: ["Flexible Aces", "Worthy Rival", "Surprising Friendship","Rival Friends","Weird Duo","Karasuno's Failing Grades Group","The Absolute King VS the Freak Duo","Number One Disciple","Similar Physique Teammates"] },
    { name: "Hinata SR",      role: "MB", img: "img-japan/hinataSR.png",      power:"Quick",                     school: "Karasuno",      bonds: ["Teammates on the Court","\"Sun\" and \"Moon\"",] },
    { name: "Kageyama UR",    role: "S",  img: "img-japan/tobioUR.png",       power:"Quick",                     school: "Karasuno",      bonds: ["The Absolute King VS the Freak Duo SP","Weird Duo","The King and The Great King","Karasuno's Setters","Karasuno's Failing Grades Group","Weird Duo (Hanami)","Karasuno's Red Mark Squad (Hanami ver.)","Karasuno Geniuses","Karasuno's Setters","The Absolute King VS the Freak Duo","Youth Camp Setters","Japan Youth Training Camp Teammates","Youth Training Camp","\"King\" and \"Great King\""] },
    { name: "Kageyama SSR",   role: "S",  img: "img-japan/tobioSSR.png",      power:"Quick",                     school: "Karasuno",      bonds: ["Teammates on the Court","Building Team Chemistry"] },
    { name: "Daichi SSR",     role: "OP", img: "img-japan/daichiSSR.png",     power:"Receive",                   school: "Karasuno",      bonds: ["Karasuno\'s Pillar","karasuno Senior Year","Behind the Smile","Karasuno 3rd Years","The Value of the 'Stage'"] },
    { name: "Daichi SR",      role: "OP", img: "img-japan/daichiSR.png",      power:"Receive",                   school: "Karasuno",      bonds: ["Karasuno\'s Pillar(practice)","Leaders Cut from the Same Cloth"] },
    { name: "Sugawara SP",    role: "S",  img: "img-japan/sugawaraSP.png",    power:"Block",                     school: "Karasuno",      bonds: ["After School","Karasuno 3rd Years","Karasuno's Setters"] },
    { name: "Sugawara SR",    role: "S",  img: "img-japan/sugawaraSR.png",    power:"Power",                     school: "Karasuno",      bonds: ["karasuno Senior Year","Karasuno's Setters",] },
    { name: "Asahi SSR",      role: "WS", img: "img-japan/asahiSSR.png",      power:"Power",                     school: "Karasuno",      bonds: ["karasuno Senior Year","\"Guardian Deity\" and \"Wing Spiker\"","Cannon \& Iron Wall","Karasuno 3rd Years","Cannon and Iron Wall"] },
    { name: "Asahi SR",       role: "WS", img: "img-japan/asahiSR.png",       power:"Power",                     school: "Karasuno",      bonds: ["\"Guardian Deity\" and \"Ace\"","Karasuno\'s Wing Spiker"] },
    { name: "Nishinoya SP",   role: "Li", img: "img-japan/nishinoyaSP.png",   power:"Receive",                   school: "Karasuno",      bonds: ["Karasuno's Red Mark Squad (Hanami ver.)","Protectors of Kiyoko","After School","Karasuno Geniuses","Team's Guardians (After School)"] },
    { name: "Nishinoya SSR",  role: "Li", img: "img-japan/nishinoyaSSR.png",  power:"Receive",                   school: "Karasuno",      bonds: ["Karasuno\'s sophomore", "Kiyoko\'s Knights","\"Guardian Deity\" and \"Wing Spiker\"","Karasuno's Failing Grades Group","Team's Guardians"] },
    { name: "Nishinoya SR",   role: "Li", img: "img-japan/nishinoyaSR.png",   power:"Receive",                   school: "Karasuno",      bonds: ["\"Guardian Deity\" and \"Ace\"","Formidable Opponent","Karasuno\'s Sophomore(practice)"] },
    { name: "Tanaka SSR",     role: "WS", img: "img-japan/tanakaSSR.png",     power:"Power",                     school: "Karasuno",      bonds: ["Karasuno\'s sophomore", "Kiyoko\'s Knights","TOMODACHI(Friends!)","Karasuno's Failing Grades Group","Karasuno's Red Mark Squad (Hanami ver.)","Protectors of Kiyoko"] },
    { name: "Tanaka SR",      role: "WS", img: "img-japan/tanakaSR.png",      power:"Receive",                   school: "Karasuno",      bonds: ["Karasuno\'s Wing Spiker","Building Team Chemistry","Karasuno\'s Sophomore(practice)"] },
    { name: "Tsukishima SP",  role: "MB", img: "img-japan/tsukishimaSP.png",  power:["Block","Quick"],           school: "Karasuno",      bonds: ["Guess vs System","Training Camp Teammates - Youth Selection","Sun vs Moon","The Moment They Fell for Volleyball","Tokyo Training Camp Buddies","Fireworks Tournament"] },
    { name: "Tsukishima SSR", role: "MB", img: "img-japan/tsukishimaSSR.png", power:["Block","Quick"],           school: "Karasuno",      bonds: ["\"Shield\" and \"Spear\"","Master and Apprentice","Prediction VS System","The Moment They Fell for Volleyball","Tokyo Training Camp Self-Practice Buddies"] },
    { name: "Tsukishima SR",  role: "MB", img: "img-japan/tsukishimaSR.png",  power:["Block","Quick"],           school: "Karasuno",      bonds: ["Simulated Junior Training Teamate","\"Shield\" and \"Spear\"(practice)","\"Sun\" and \"Moon\""] },
    { name: "Tadashi SR",     role: "MB", img: "img-japan/tadashiSR.png",                                        school: "Karasuno",      bonds: ["\"Shield\" and \"Spear\"",] },
    { name: "Tadashi R",      role: "MB", img: "img-japan/tadashiR.png",                                         school: "Karasuno",      bonds: ["\"Shield\" and \"Spear\"(practice)"] },
    { name: "Chikara SR",     role: "WS", img: "img-japan/chikaraSR.png",     power:"Receive",                   school: "Karasuno",      bonds: ["Karasuno\'s sophomore", "Karasuno\'s Pillar","The Returning Trio"] },
    { name: "Chikara R",      role: "WS", img: "img-japan/chikaraR.png",      power:"Receive",                   school: "Karasuno",      bonds: ["Karasuno\'s Wing Spiker","Karasuno\'s Pillar(practice)","Karasuno\'s Sophomore(practice)"] },
    { name: "Hisashi R",      role: "WS", img: "img-japan/hisashiR.png",                                         school: "Karasuno",      bonds: ["Bench cheer","The Returning Trio"] },
    { name: "Kazuhito R",     role: "MB", img: "img-japan/kazuhitoR.png",     power:"Quick",                     school: "Karasuno",      bonds: ["Bench cheer","The Returning Trio"] },
    { name: "Kageyama SR",    role: "S",  img: "img-japan/tobioSR.png",                                          school: "Kitagawa",      bonds: [] },

    { name: "Oikawa SP",      role: "S",  img: "img-japan/oikawaSP.png",      power:"Power",                     school: "Aoba Johsai",   bonds: ["Aoba Johsai Third Years","\"King\" and \"Great King\"","In Perfect Sync","Culture Festival","Toward Greater Heights","Merciless Trust(SP)","Rivals by Fate"] },
    { name: "Oikawa UR",      role: "S",  img: "img-japan/oikawaUR.png",      power:"Power",                     school: "Aoba Johsai",   bonds: ["The King and The Great King","To Greater Heights","Breath of Aoba","Fated Rivals","Merciless Trust"] },
    { name: "Oikawa SSR",     role: "S",  img: "img-japan/oikawaSSR.png",     power:"Power",                     school: "Aoba Johsai",   bonds: ["Team Chemistry"] },
    { name: "Iwaizumi SP",    role: "WS", img: "img-japan/iwaizumiSP.png",    power:["Power","Receive"],         school: "Aoba Johsai",   bonds: ["Aoba Johsai Wing Spikers","Aoba Johsai Third Years","Wolf Society","In Perfect Sync","Culture Festival"] },    
    { name: "Iwaizumi SSR",   role: "WS", img: "img-japan/iwaizumiSSR.png",   power:"Power",                     school: "Aoba Johsai",   bonds: ["The Wolf Pack","Breath of Aoba"] },
    { name: "Iwaizumi SR",    role: "WS", img: "img-japan/iwaizumiSR.png",    power:"Power",                     school: "Aoba Johsai",   bonds: ["The Wolf Pack(Practice)","Team Chemistry"] },
    { name: "Matsukawa SR",   role: "MB", img: "img-japan/matsukawaSR.png",   power:["Quick","Block"],           school: "Aoba Johsai",   bonds: ["Aoba Johsai Third Years","Seijoh\'s Senior Year Pillars","Toward Greater Heights"] },
    { name: "Hanamaki SR",    role: "WS", img: "img-japan/hanamakiSR.png",    power:["Power","Receive"],         school: "Aoba Johsai",   bonds: ["Aoba Johsai Wing Spikers","Aoba Johsai Third Years","Seijoh\'s Senior Year Pillars"] },
    { name: "Yahaba SR",      role: "S",  img: "img-japan/yahabaSR.png",      power:"Power",                     school: "Aoba Johsai",   bonds: ["Aoba Johsai's Sophomore","Hidden Fire"] },
    { name: "Watari SR",      role: "Li", img: "img-japan/watariSR.png",      power:"Receive",                   school: "Aoba Johsai",   bonds: ["Aoba Johsai's Sophomore"] },
    { name: "Kindaichi SR",   role: "MB", img: "img-japan/kindaichiSR.png",   power:["Block","Quick"],           school: "Aoba Johsai",   bonds: ["Blunt and Composed","To Greater Heights","Calm and honest"] },
    { name: "Kunimi SP",      role: "OP", img: "img-japan/kunimiSP.png",      power:["Power","Receive"],         school: "Aoba Johsai",   bonds: ["Aoba Johsai Wing Spikers","Calm and honest","Sports Festival"] },
    { name: "Kunimi SR",      role: "OP", img: "img-japan/kunimiSR.png",      power:["Power","Receive"],         school: "Aoba Johsai",   bonds: ["Blunt and Composed"] },
    { name: "Kentaro SSR",    role: "OP", img: "img-japan/kyotaniSSR.png",    power:"Power",                     school: "Aoba Johsai",   bonds: ["Aoba Johsai Wing Spikers","Wolf Society","Aoba Johsai's Sophomore","Hidden Fire","The Wolf Pack","Merciless Trust","Merciless Trust(SP)"] },
    { name: "Kentaro SR",     role: "OP", img: "img-japan/kyotaniSR.png",     power:"Power",                     school: "Aoba Johsai",   bonds: ["The Wolf Pack(Practice)"] },

    { name: "Kenma SP",       role: "S",  img: "img-japan/kenmaSP.png",       power:"Receive",                   school: "Nekoma",        bonds: ["Hanami","Perseverance and Tenacity"] },
    { name: "Kenma SSR",      role: "S",  img: "img-japan/kenmaSSR.png",      power:"Receive",                   school: "Nekoma",        bonds: ["Rival Friends","\"Brain\" and \"Control Tower\"","Grit and Competitive","The \"Enigmatic\" Teammate"] },
    { name: "Kenma SR",       role: "S",  img: "img-japan/kenmaSR.png",       power:"Receive",                   school: "Nekoma",        bonds: ["\"Pivot\" and \"Defensive Pivot\"","\"Pivot\" and \"Control Tower\""] },
    { name: "Kuroo SP",       role: "MB", img: "img-japan/kurooSP.png",       power:["Receive","Block"],         school: "Nekoma",        bonds: ["Tokyo Training Camp Buddies","Fireworks Tournament"] },
    { name: "Kuroo UR",       role: "MB", img: "img-japan/kurooUR.png",       power:["Quick","Block"],           school: "Nekoma",        bonds: ["Behind the Smile","Master and Apprentice","\"Brain\" and \"Control Tower\"","Reliable Seniors","Tokyo Training Camp Self-Practice Buddies"] },
    { name: "Kuroo SSR",      role: "MB", img: "img-japan/kurooSSR.png",      power:["Quick","Block"],           school: "Nekoma",        bonds: ["Leaders Cut from the Same Cloth","\"Pivot\" and \"Control Tower\""] },
    { name: "Yaku SR",        role: "Li", img: "img-japan/yakuSR.png",        power:"Receive",                   school: "Nekoma",        bonds: ["Formidable Opponent","One-on-One Training","\"Pivot\" and \"Defensive Pivot\""] },
    { name: "Yaku SSR",       role: "Li", img: "img-japan/yakuSSR.png",       power:"Receive",                   school: "Nekoma",        bonds: ["Team's Guardians","Team's Guardians (After School)","Reliable Seniors","Protective Guidance"] },
    { name: "Lev SSR",        role: "MB", img: "img-japan/levSSR.png",        power:["Block","Quick"],           school: "Nekoma",        bonds: ["Flexible Aces","Nekoma\'s Junior","The \"Enigmatic\" Teammate","Protective Guidance"] },
    { name: "Lev SR",         role: "MB", img: "img-japan/levSR.png",         power:"Quick",                     school: "Nekoma",        bonds: ["One-on-One Training"] },
    { name: "Yamamoto SR",    role: "WS", img: "img-japan/yamamotoSR.png",    power:"Power",                     school: "Nekoma",        bonds: ["TOMODACHI(Friends!)","Nekoma\'s Wing Spiker","Grit and Competitive","Perseverance and Tenacity"] },
    { name: "Kai SR",         role: "OP", img: "img-japan/kaiSR.png",         power:"Receive",                   school: "Nekoma",        bonds: ["Nekoma\'s Wing Spiker","Reliable Seniors"] },
    { name: "Fukunaga SR",    role: "WS", img: "img-japan/fukunagaSR.png",    power:["Power","Receive"],         school: "Nekoma",        bonds: ["Nekoma\'s Wing Spiker"] },
    { name: "Inuoka SR",      role: "MB", img: "img-japan/inuokaSR.png",      power:"Block",                     school: "Nekoma",        bonds: ["Worthy Rival","Nekoma\'s Junior"] },
    { name: "Teshiro SR",     role: "S",  img: "img-japan/teshiroSR.png",     power:"Receive",                   school: "Nekoma",        bonds: ["Nekoma\'s Junior"] },

    { name: "Aone SP",        role: "MB", img: "img-japan/aoneSP.png",        power:"Block",                     school: "Date Kogyo",    bonds: ["The New “Iron Wall”","Silence and Sarcasm","Beach","Cannon and Iron Wall","Strange Friendship"] },
    { name: "Aone SSR",       role: "MB", img: "img-japan/aoneSSR.png",       power:["Quick","Block"],           school: "Date Kogyo",    bonds: ["Cannon \& Iron Wall","Surprising Friendship","The Silent and the Snarky"] },
    { name: "Aone SR",        role: "MB", img: "img-japan/aoneSR.png",        power:"Block",                     school: "Date Kogyo",    bonds: [] },
    { name: "Kenji SSR",      role: "WS", img: "img-japan/kenjiSSR.png",      power:"Block",                     school: "Date Kogyo",    bonds: ["The New “Iron Wall”","The Big Rookie and the New Captain","Date Kogyo\'s Captains","The Silent and the Snarky","New Captain \& Tall Rookie","Silence and Sarcasm"] },
    { name: "Kenji SR",       role: "WS", img: "img-japan/kenjiSR.png",       power:["Power","Block"],           school: "Date Kogyo",    bonds: [] },
    { name: "Kanji SP",       role: "S",  img: "img-japan/kanjiSP.png",       power:"Block",                     school: "Date Kogyo",    bonds: ["The New “Iron Wall”","The Big Rookie and the New Captain","Training Camp Teammates - Youth Selection","Date Tech’s Setter","Sports Festival"] },
    { name: "Kanji SSR",      role: "S",  img: "img-japan/kanjiSSR.png",      power:"Block",                     school: "Date Kogyo",    bonds: ["New Captain \& Tall Rookie","Date Kogyo\'s Setter",] },
    { name: "Kanji SR",       role: "S",  img: "img-japan/kanjiSR.png",       power:"Block",                     school: "Date Kogyo",    bonds: ["Simulated Junior Training Teamate"] },
    { name: "Sakunami R",     role: "Li", img: "img-japan/sakunamiR.png",     power:"Receive",                   school: "Date Kogyo",    bonds: ["Date Kogyo\'s Junior"] },
    { name: "Kamasaki SR",    role: "MB", img: "img-japan/kamasakiSR.png",    power:["Block","Quick"],           school: "Date Kogyo",    bonds: ["Date Kogyo\'s Senior"] },
    { name: "Kaname SR",      role: "S",  img: "img-japan/kanameSR.png",      power:"Block",                     school: "Date Kogyo",    bonds: ["Date Tech’s Setter","Date Kogyo\'s Captains","Date Kogyo\'s Setter","Date Kogyo\'s Senior",] },
    { name: "Sasaya SSR",     role: "OP", img: "img-japan/takehitoSSR.png",   power:"Power",                     school: "Date Kogyo",    bonds: ["Date Kogyo\'s Wing Spiker","Date Kogyo\'s Senior"] },
    { name: "Sasaya SR",      role: "OP", img: "img-japan/takehitoSR.png",    power:"Power",                     school: "Date Kogyo",    bonds: [] },
    { name: "Yutaka SR",      role: "WS", img: "img-japan/yutakaSR.png",      power:["Block","Receive"],         school: "Date Kogyo",    bonds: ["Date Kogyo\'s Wing Spiker"] },
    { name: "Jingo R",        role: "MB", img: "img-japan/jingoR.png",        power:["Receive","Block"],         school: "Date Kogyo",    bonds: ["Date Kogyo\'s Junior"] },
    { name: "Taro R",         role: "OP", img: "img-japan/taroR.png",         power:"Block",                     school: "Date Kogyo",    bonds: [] },

    { name: "Ushijima SP",    role: "OP", img: "img-japan/ushijimaSP.png",    power:"Power",                     school: "Shiratorizawa", bonds: ["From the Great Ace to the Next Ace","Ushiwaka and Benkei SP","The Absolute King and the Steadfast Setter SP","The Absolute King VS the Freak Duo SP","Shiratorizawa 3rd Years SP","Rivals by Fate","Culture Festival","Lifelong Best Friends SP"] },
    { name: "Ushijima UR",    role: "OP", img: "img-japan/ushijimaUR.png",    power:"Power",                     school: "Shiratorizawa", bonds: ["Lifelong Best Friends","Undisputed Aces","Fated Rivals","Ushiwaka and Benkei","The Absolute King and the Steadfast Setter","The Absolute King VS the Freak Duo","Shiratorizawa 3rd Years"] },
    { name: "Goshiki SSR",    role: "WS", img: "img-japan/goshikiSSR.png",    power:"Block",                     school: "Shiratorizawa", bonds: ["From the Great Ace to the Next Ace","Expectations of a senior","Promising Senpai","Undisputed Aces","Shiratorizawa's WS"] },
    { name: "Tendo SP",       role: "MB", img: "img-japan/tendoSP.png",       power:"Block",                     school: "Shiratorizawa", bonds: ["Shiratorizawa\'s Middle Blocker SP","Shiratorizawa 3rd Years SP","Expectations of a senior","Guess vs System","Lifelong Best Friends SP"] },
    { name: "Tendo SSR",      role: "MB", img: "img-japan/tendoSSR.png",      power:"Block",                     school: "Shiratorizawa", bonds: ["Lifelong Best Friends","Promising Senpai","Shiratorizawa\'s Middke Blocker","Prediction VS System","Shiratorizawa 3rd Years"] },
    { name: "Taichi SR",      role: "MB", img: "img-japan/kawanishiSR.png",   power:"Block",                     school: "Shiratorizawa", bonds: ["Shiratorizawa\'s Middle Blocker SP","Shiratorizawa\'s Middke Blocker","Shiratorizawa 2nd Years"] },
    { name: "Shirabu SSR",    role: "S",  img: "img-japan/shirabuSSR.png",    power:"Power",                     school: "Shiratorizawa", bonds: ["The Absolute King and the Steadfast Setter SP","The Absolute King and the Steadfast Setter","Shiratorizawa 2nd Years","Setters of Different Types"] },
    { name: "Semi SSR",       role: "S",  img: "img-japan/semiSSR.png",       power:"Power",                     school: "Shiratorizawa", bonds: ["Shiratorizawa 3rd Years SP","Shiratorizawa 3rd Years","Setters of Different Types"] },
    { name: "Ohira SSR",      role: "WS", img: "img-japan/ohiraSSR.png",      power:"Receive",                   school: "Shiratorizawa", bonds: ["Ushiwaka and Benkei SP","Shiratorizawa 3rd Years SP","Ushiwaka and Benkei","Shiratorizawa 3rd Years","Shiratorizawa's WS"] },
    { name: "Yamagata SSR",   role: "Li", img: "img-japan/yamagataSSR.png",   power:"Receive",                   school: "Shiratorizawa", bonds: ["Shiratorizawa 3rd Years SP","Shiratorizawa 3rd Years"] },

    { name: "Bokuto SP",      role: "WS", img: "img-japan/bokutoSP.png",      power:["Receive","Power"],         school: "Fukurodani",    bonds: ["Number One Disciple SP","The Moment They Fell for Volleyball","Beach",,"Kizuna Skills","Miracle Ace & Considerate Setter","Tokyo Training Camp Buddies"] },
    { name: "Bokuto UR",      role: "WS", img: "img-japan/bokutoUR.png",      power:"Power",                     school: "Fukurodani",    bonds: ["The Moment They Fell for Volleyball","Tokyo Training Camp Self-Practice Buddies","Miracle Ace and the Stubborn Setter","Number One Disciple","Fukurodani WS","Fukurodani 3rd Years"] },
    { name: "Akaashi SP",     role: "S",  img: "img-japan/akaashiSP.png",     power:"Power",                     school: "Fukurodani",    bonds: ["Beach","Kizuna Skills","Miracle Ace & Considerate Setter","Tokyo Training Camp Buddies"] },
    { name: "Akaashi SSR",    role: "S",  img: "img-japan/akaashiSSR.png",    power:"Power",                     school: "Fukurodani",    bonds: ["Tokyo Training Camp Self-Practice Buddies","Miracle Ace and the Stubborn Setter"] },
    { name: "Konoha SSR",     role: "OP", img: "img-japan/konohaSSR.png",     power:"Receive",                   school: "Fukurodani",    bonds: ["Fukurodani 3rd Years"] },
    { name: "Sarukui SR",     role: "WS", img: "img-japan/sarukuiSR.png",     power:["Receive","Power"],         school: "Fukurodani",    bonds: ["Fukurodani WS","Fukurodani 3rd Years"] },
    { name: "Komi SSR",       role: "Li", img: "img-japan/komiSSR.png",       power:"Receive",                   school: "Fukurodani",    bonds: ["Fukurodani 3rd Years"] },
    { name: "Onaga R",        role: "MB", img: "img-japan/onagaR.png",        power:"Block",                     school: "Fukurodani",    bonds: ["Fukurodani MBs"] },
    { name: "Washio SSR",     role: "MB", img: "img-japan/washioSSR.png",     power:["Block","Quick"],           school: "Fukurodani",    bonds: ["Fukurodani MBs","Fukurodani 3rd Years"] },

    { name: "Terushima SSR",  role: "WS", img: "img-japan/terushimaSSR.png",  power:"Power",                     school: "Johzenji",      bonds: ["The Value of the 'Stage'","Two High-Energy Guys","Jouzenji's WS"] },
    { name: "Bobata R",       role: "MB", img: "img-japan/bobataR.png",       power:"Block",                     school: "Johzenji",      bonds: ["Two High-Energy Guys"] },
    { name: "Futamata SR",    role: "S",  img: "img-japan/futamataSR.png",    power:"Power",                     school: "Johzenji",      bonds: [] },
    { name: "Higashiyama SR", role: "WS", img: "img-japan/higashiyamaSR.png", power:["Receive","Power"],         school: "Johzenji",      bonds: ["Jouzenji's WS"] },
    { name: "Izaka R",        role: "MB", img: "img-japan/izakaR.png",        power:"Block",                     school: "Johzenji",      bonds: [] },
    { name: "Numajiri R",     role: "OP", img: "img-japan/numajiriR.png",     power:"Receive",                   school: "Johzenji",      bonds: [] },
    { name: "Tsuchiyu R",     role: "Li", img: "img-japan/tsuchiyuR.png",     power:"Receive",                   school: "Johzenji",      bonds: [] },

    { name: "Kita SSR",       role: "WS", img: "img-japan/kitaSSR.png",       power:"Receive",                   school: "Inarizaki",     bonds: ["Head and Core","Third Year from Inarizaki","Inarizaki WS Teammates"] },
    { name: "Omimi SR",       role: "MB", img: "img-japan/omimiSR.png",       power:"Block",                     school: "Inarizaki",     bonds: ["Inarizaki's Middle Blockers","Third Year from Inarizaki"] },
    { name: "Ojiro SSR",      role: "WS", img: "img-japan/ojiroSSR.png",      power:"Power",                     school: "Inarizaki",     bonds: ["Friends from Volleyball Class","Third Year from Inarizaki","Inarizaki WS Teammates"] },
    { name: "Ginjima SSR",    role: "WS", img: "img-japan/ginjimaSSR.png",    power:["Receive","Power"],         school: "Inarizaki",     bonds: ["Inarizaki 2nd Years","Inarizaki WS Teammates"] },
    { name: "Atsumu UR",      role: "S",  img: "img-japan/atsumuUR.png",      power:"Quick",                     school: "Inarizaki",     bonds: ["Head and Core","Youth Camp Setters","Strongest High School Twins","Friends from Volleyball Class","Inarizaki 2nd Years","Japan Youth Training Camp Teammates"] },
    { name: "Suna SSR",       role: "MB", img: "img-japan/sunaSSR.png",       power:["Block","Quick"],           school: "Inarizaki",     bonds: ["Classmates","Inarizaki's Middle Blockers","Inarizaki 2nd Years"] },
    { name: "Osamu UR",       role: "OP", img: "img-japan/osamuUR.png",       power:"Quick",                     school: "Inarizaki",     bonds: ["Head and Core","Strongest High School Twins","Classmates","Friends from Volleyball Class","Inarizaki 2nd Years"] },
    { name: "Kosaku R",       role: "WS", img: "img-japan/kosakuR.png",       power:"Receive",                   school: "Inarizaki",     bonds: ["Inarizaki 2nd Years","Inarizaki WS Teammates"] },
    { name: "Riseki R",       role: "WS", img: "img-japan/risekiR.png",       power:"Power",                     school: "Inarizaki",     bonds: ["Inarizaki WS Teammates"] },
    { name: "Akagi SSR",      role: "Li", img: "img-japan/akagiSSR.png",      power:"Receive",                   school: "Inarizaki",     bonds: ["Third Year from Inarizaki",] },
   
    { name: "Hoshiumi UR",    role: "WS", img: "img-japan/hoshiumiUR.png",    power:["Block","Receive","Power"], school: "Kamomedai",     bonds: ["Similar Builds","Japan Youth Training Camp Teammates","Youth Training Camp","Similar Physique Teammates","Friends from Junior High"] },
    { name: "Hirugami UR",    role: "MB", img: "img-japan/hirugamiUR.png",    power:"Block",                     school: "Kamomedai",     bonds: ["Friends from Junior High"] },

    { name: "Sakusa UR",      role: "WS", img: "img-japan/sakusaUR.png",      power:["Receive","Power"],         school: "Itachiyama",    bonds: ["Japan Youth Training Camp Teammates","Top Spiker and Top-Class Libero"] },
    { name: "Komori UR",      role: "Li", img: "img-japan/komoriUR.png",      power:"Receive",                   school: "Itachiyama",    bonds: ["Japan Youth Training Camp Teammates","Top Spiker and Top-Class Libero"] },

];
// tempalte: "": "",
const synergyDescriptions = {
    "Karasuno": "Increases Power Attack and Quick Attack stats of all players present by 10%",
    "Shiratorizawa": "Increases Awareness and Strength of all players present by 10%",
    "Aoba Johsai": "Increases Power Attack stats of all players present by 15%",
    "Nekoma": "Increases Receive stat of all players present by 15%",
    "Date Kogyo": "Increases Block stat of all players present by 15%",
    "Fukurodani": "When 4 or more members from Fukurōdani Academy are on the court, the team's Morale increases by 20.",
    "Jozenji": " all allies gain 2 stacks of [Play More]. Each stack of [Play More] increases Power Attack and Quick Attack by 2.5%, up to 4 stacks.",
    "Inarizaki": "Increases Attack and Defense stat of all players present +5%",

    //karasuno bond
    "Karasuno\'s Pillar": "When achieving a PERFECT receive, increases Team Morale by 3/3/4/4/5",
    "Flexible Aces": { "Hinata SSR": "Block +5/7/9/12/15, Block +1/2/3/4/5%", "Lev SSR": "Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%"},
    "Worthy Rival": {"Hinata SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%", "Inuoka SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%"},
    "Kiyoko\'s Knights": "When scoring,su increases Team morale by 6/7/8/9/10",
    "karasuno Senior Year": "Reduces Stamina consumption of Spike skills by 10%; when performing Power Spikes, increases this player\'s Attack Technique by 6/7/8/9/10%",
    "\"Guardian Deity\" and \"Wing Spiker\"": "When Nishinoya or Asahi casts a skill, increases their Attack Technique and Defense Technique by 6/7/8/9/10%",
    "\"Shield\" and \"Spear\"":"Increases Tsukishima\'s Block stat by 6/7/8/9/10% and Tadashi\'s Serve stat by 6/7/8/9/10%",
    "TOMODACHI(Friends!)":{"Yamamoto SR": "Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%","Tanaka SSR": "Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%"},
    "Cannon \& Iron Wall": {"Asahi SSR": "Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%","Aone SSR":"No buff"},
    "Karasuno\'s sophomore": {"Chikara SR":"Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%", "Nishinoya SSR": "Set +5/7/9/12/15, Set +1/2/3/4/5%", "Tanaka SSR":"Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%"},
    "\"Guardian Deity\" and \"Ace\"":"When Nishinoya or Asahi casts a skill, increases their Attack Technique by 6/7/8/9/10%",
    "Leaders Cut from the Same Cloth": {"Daichi SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Kuroo SSR": "Block +5/7/9/12/15, Block +1/2/3/4/5%"},
    "Surprising Friendship":{"Aone SSR": "Block +5/7/9/12/15, Block +1/2/3/4/5%","Hinata SSR":"No buff"},
    "Karasuno\'s Wing Spiker":{"Tanaka SR":"Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%", "Asahi SR": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%", "Chikara SR":"Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%"},
    "Teammates on the Court": "When casting Quick Spike skills, increases this player's Awareness ny 6/7/8/9/10%",
    "Simulated Junior Training Teamate": {"Kanji SR":"Set +5/7/9/12/15, Set +1/2/3/4/5%","Tsukishima SR": "No buff"},
    "Karasuno\'s Pillar(practice)": {"Chikara R": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Daichi SR":"Block +5/7/9/12/15, Block +1/2/3/4/5%"},
    "\"Shield\" and \"Spear\"(practice)": "Increases Tsukishima\'s Block stat by 6/7/8/9/10% and Tadashi\'s Serve stat by 6/7/8/9/10%",
    "Formidable Opponent": {"Nishinoya SR":" Save +5/7/9/12/15, Save +1/2/3/4/5%","Yaku SR":" Set +5/7/9/12/15, Set +1/2/3/4/5%"},
    "Bench cheer" : {"Hisashi R": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%", "Kazuhito R": "Block +5/7/9/12/15, Block +1/2/3/4/5%" },
    "The Returning Trio":{"Hisashi R":"Set +5/7/9/12/15, Set +1/2/3/4/5%","Kazuhito R":"Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%","Chikara SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%"},
    "\"Sun\" and \"Moon\"": {"Tsukishima SR": "Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%", "Hinata SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%" },
    "Building Team Chemistry": {"Kageyama SSR": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%", "Tanaka SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%" },
    "Karasuno\'s Sophomore(practice)":"Increases Receive stat of back row players 6/7/8/9/10%",
    "Rival Friends": {"Hinata SSR": "Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%", "Kenma SSR": "Set +5/7/9/12/15, Set +1/2/3/4/5%" },
    "Behind the Smile": {"Daichi SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%", "Kuroo UR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%" },
    "Master and Apprentice": {"Tsukishima SSR": "Block +5/7/9/12/15, Block +1/2/3/4/5%","Kuroo UR": "Block +5/7/9/12/15, Block +1/2/3/4/5%"},
    "Weird Duo": "Hinata performs a Quick Attack with 280/295/310/325/340% Speed. Awareness +30%, Power +(Awareness ×30/35/40/45/50%, max 60/70/80/90/100%). Cannot be blocked. Resets cooldown on scoring.",
    "The King and The Great King": {"Kageyama UR": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%","Oikawa UR": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%"},
    "Karasuno's Setters": {"Sugawara SR": "Toss +5/7/9/12/15, Toss +1/2/3/4/5%","Kageyama SSR": "Toss +5/7/9/12/15, Toss +1/2/3/4/5%"},
    "Karasuno's Failing Grades Group": {"Hinata SSR": "","Kageyama UR": "","Nishinoya SSR": "","Tanaka SSR": "Strong Attack +5/7/9/12/15, Strong Attack +1/2/3/4/5%"},
    "Team's Guardians": {"Nishinoya SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Yaku SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%"},
    "Similar Builds": {"Hinata SP": "Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%","Hoshiumi UR": "Strong Attack +5/7/9/12/15, Strong Attack +1/2/3/4/5%"},
    "Weird Duo (Hanami)": "When an ally uses a Receive skill, consumes 1 [Never Give Up] stack to increase their Reaction by 6%. If Hinata (Hanami) uses Receive, his Reaction increases by an additional 9% and Kageyama gains 1 stack of [Never Give Up]. Hinata (Hanami)'s Special also grants Kageyama 1 stack of [Never Give Up].",
    "Hanami": "At match start, Kenma (Hanami) gains 3 [Gapless Defense] stacks and increases the cap to 13; each stack increases his Awareness by 0.8%. When Hinata (Hanami) makes a Nice Play, his Quick Attack increases by 1%.",
    "Strange Friendship": {"Hinata SP": "Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%","Aone SP": "Block +5/7/9/12/15, Block +1/2/3/4/5%"},
    "Number One Disciple SP": {"Hinata SP": "Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%","Bokuto SP": "Strong Attack +5/7/9/12/15, Strong Attack +1/2/3/4/5%"},
    "Karasuno's Red Mark Squad (Hanami ver.)": {"Hinata SP": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Nishinoya SP": "Toss +5/7/9/12/15, Toss +1/2/3/4/5%","Tanaka SSR": "","Kageyama UR": ""},
    "Protectors of Kiyoko": {"Nishinoya SP": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Tanaka SSR": "Spike +5/7/9/12/15, Spike +1/2/3/4/5%"},
    "After School": "Increases Nishinoya (After School)'s Reaction by 5%; if Sugawara (After School) is on the court and Nishinoya (After School)'s Stamina is below 80, his Reaction increases by an additional 5%",
    "Karasuno Geniuses": "Increases Nishinoya (After School)'s Receive by 5% and Reaction by 5%. When Nishinoya (After School) uses his Ultimate, Kageyama gains 1 stack of [Hates to Lose]. If this Ultimate is a Nice Play, then after the play, the first ally Spike (Power/Quick) increases its power by 20% for the spiker.",
    "Team's Guardians (After School)": {"Nishinoya SP": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Yaku SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%"},
    "Sun vs Moon": "When allies perform a Toss, increases their Awareness by 10% until the ball crosses the net twice. If Hinata (Hanami)'s Quick Attack results in a Nice Play, the cooldown of [High Jump] is reduced by 2 net crossings. Tsukishima (Fireworks) gains Awareness equal to 50% of Hinata (Hanami)'s Awareness, up to 50%. Effect lasts until the ball crosses the net 4 times.",
    "Karasuno 3rd Years": {"Asahi SSR": "Power +5/7/9/12/15, Power +1/2/3/4/5%","Daichi SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Sugawara SP": "Block +5/7/9/12/15, Block +1/2/3/4/5%"},
    "Karasuno's Setters": {"Sugawara SP": "Toss +5/7/9/12/15, Toss +1/2/3/4/5%","Kageyama UR": ""},
    "The Moment They Fell for Volleyball": {"Bokuto SP": "Spikes +5/7/9/12/15, Spikes +1/2/3/4/5%","Tsukishima SP": "Quick +5/7/9/12/15, Quick +1/2/3/4/5%"},
    "Friends from Volleyball Class":{"Atsumu UR":"Serve +5/7/9/12/15, Serve +1/2/3/4/5%", "Osamu UR":"Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%", "Ojiro SSR":"Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%"},
    "Fireworks Tournament": "Allies' main stats +6%. After each rally, inflicts [Anger] on enemy front row (-10% Power/Speed) for 8 net passes. If already [Anger]ed, applies [Tantrum] instead (-20% Power/Speed, cannot be cleansed).",

    //Aoba Johsai
    "Aoba Johsai's Sophomore": {"Watari SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%", "Yahaba SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%", "Kentaro SSR": "No buff" },
    "Blunt and Composed":"Increases Kindaichi\'s Quick Attack stat by 6/7/8/9/10% and  Kunimi\'s Power Attack stat by 6/7/8/9/10%",
    "The Wolf Pack":"Increases  Iwaizumi and Kentaro\'s Power Attack stat by 6/7/8/9/10%",
    "Hidden Fire":{"Kentaro SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Yahaba SR": "No buff"},
    "Seijoh\'s Senior Year Pillars": "Increases Matsukawa\'s Block stat by 6/67/8/9/10% and Hanamaki\'s Receive stat by 6/7/8/9/10%",
    "The Wolf Pack(Practice)": "Increases Iwaisumi and Kentaro's Awareness by 6/7/8/9/10%",
    "Team Chemistry" : "Increases Oikawa and Iwaizumi's Awareness by 6/7/8/9/10%",
    "To Greater Heights": {"Kindaichi SR": "","Oikawa UR": "Toss +5/7/9/12/15, Toss +1/2/3/4/5%"},
    "Breath of Aoba": "When Oikawa performs a toss, Iwaizumi performs a Spike with 255% Attack power. Gains 2 stacks of [Attack Rhythm]. For each stack of [Attack Rhythm], all allies' Awareness increases by 1%. Max 10 stacks.",
    "Merciless Trust": {"Oikawa UR": "Block +5/7/9/12/15, Block +1/2/3/4/5%","Kentaro SSR": "Spike +5/7/9/12/15, Spike +1/2/3/4/5%"},
    "Merciless Trust(SP)":  {"Oikawa SP": "Spike +5/7/9/12/15, Spike +1/2/3/4/5%","Kentaro SSR": "Spike +5/7/9/12/15, Spike +1/2/3/4/5%"},
    "Fated Rivals": {"Oikawa UR": "Toss +5/7/9/12/15, Toss +1/2/3/4/5%", "Ushijima UR": ""},
    "Calm and honest":{"Kunimi SP": "Spike +5/7/9/12/15, Spike +1/2/3/4/5%", "Kindaichi SR": "Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%"},
    "Toward Greater Heights" : {"Oikawa SP": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%","Kindaichi SR": "Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%"},
    "\"King\" and \"Great King\"" : "When Tobio Kageyama and Toru Oikawa (Cultural Festival) compete for serve control, the one who activates their serve skill first wins the duel. If Oikawa (Cultural Festival) wins, Kageyama gains the [Motivated] effect. This effect lasts for 1 set. If Kageyama wins, then each time Oikawa (Cultural Festival) touches the ball, Kageyama gains 1 stack of the [Hates to Lose] effect. Additionally, when Oikawa (Cultural Festival) activates his skill, Kageyama gains 1 more stack of the [Hates to Lose] effect.",
    "Rivals by Fate":"When Ushijima Wakatoshi (Culture Festival) has the [Unleashed] effect, Oikawa Tōru (Culture Festival)’s [Toss] and [Serve] increase by 6/7/8/9/10%. When Oikawa (Culture Festival) performs a toss and Ushijima (Culture Festival) performs a spike, they gain 1 stack of [Attack Rhythm]. Each stack of [Attack Rhythm] increases all allies’ [Awareness] on the same court by 1%. Up to 10 stacks.",
    "Culture Festival":"When a member with the [Unleashed] effect touches the ball, Oikawa Tōru (Culture Festival) and all members with [Unleashed] recover 2 stamina. At the start of a rally, for each [Culture Festival] member on your court, all allies gain +2/2.5/3/3.5/4% [Power] and [Mental]. Maximum bonus: +12/15/18/21/24%.",
    "In Perfect Sync":"When Oikawa Tōru (Culture Festival) performs a toss and Iwaizumi Hajime (Culture Festival) spikes, the spike deals damage with 280/300/320/340/360% power. Iwaizumi (Culture Festival) gains the [Unleashed] effect. This effect lasts for one set.",
    "Wolf Society":{"Iwaizumi SP": "Spike +5/7/9/12/15, Spike +1/2/3/4/5%", "Kentaro SSR": "Spike +5/7/9/12/15, Spike +1/2/3/4/5%"},
    "Aoba Johsai Third Years":{"Oikawa SP": "Toss +5/7/9/12/15, Toss +1/2/3/4/5%","Iwaizumi SP": "Spike +5/7/9/12/15, Spike +1/2/3/4/5%","Matsukawa SR": "Block +5/7/9/12/15, Block +1/2/3/4/5%","Hanamaki SR": "Spike +5/7/9/12/15, Spike +1/2/3/4/5%"},
    "Aoba Johsai Wing Spikers":{"Iwaizumi SP": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Hanamaki SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Kunimi SP": "Spike +5/7/9/12/15, Spike +1/2/3/4/5%","Kentaro SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%"},
    //Nekoma
    "Nekoma\'s Junior":{"Teshiro SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Inuoka SR": "No buff", "Lev SSR":"No Buff"},
    "\"Brain\" and \"Control Tower\"":"Kenma sets the ball, Kuroo performs a Quick Spike with 265/280/295/310/325% of Quick Attack stat as power",
    "Nekoma\'s Wing Spiker":"Increases Receive and Power Attack stats of players present by 4/5/6/7/8%",
    "Grit and Competitive":{"Yamamoto SR": "No buff","Kenma SSR": "Set +5/7/9/12/15, Set +1/2/3/4/5%"},
    "One-on-One Training":{"Lev SR": "Block +5/7/9/12/15, Block +1/2/3/4/5%","Yaku SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%"},
    "The \"Enigmatic\" Teammate":{"Lev SSR": "Block +5/7/9/12/15, Block +1/2/3/4/5%","Kenma SSR": "No buff"},
    "\"Pivot\" and \"Defensive Pivot\"":{"Yaku SR": "Save +5/7/9/12/15, Save +1/2/3/4/5%","Kenma SSR": "Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%"},
    "\"Pivot\" and \"Control Tower\"":"Increases Kenma\'s Set stat by 6/7/8/9/10% and Kuroo\'s Block Stat by 6/7/8/9/10%",
    "Reliable Seniors": {"Kuroo UR": "Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%","Yaku SSR": "","Kai SR": ""},
    "Protective Guidance": "increases Yaku receive by 6% and Lev Quick Attack by 6%",
    "Perseverance and Tenacity": {"Kenma SP": "Toss +5/7/9/12/15, Toss +1/2/3/4/5%","Yamamoto SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%"},

    //Date Kogyo
    "Date Kogyo\'s Captains":{"Kaname SR":"No buff","Kenji SSR":"Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%"},
    "The Silent and the Snarky":"Aone and Kenji perform a Double block with 180/195/210/225/240% of Aone\'s Block stat as power;applies \"Enrage\" Debuff to opponent spiker \(reduces Power\/Quick Attack stats by 10%\)",
    "New Captain \& Tall Rookie":"Increases Block stat of front row players by 2/2.5/3/3.5/4%",
    "Date Kogyo\'s Wing Spiker":"Increases Yutaka\'s Block stat by 2/2.5/3/3.5/4% and Takehito\'s Power Attack stat by 2/2.5/3/3.5/4%",
    "Date Kogyo\'s Setter":{"Kaname SR":"No buff","Kaji SSR":"Set +5/7/9/12/15, Set +1/2/3/4/5%"},
    "Date Kogyo\'s Junior":{"Jingo R":"Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Sakunami R":"Quick Attack +5/7/9/12/15, Quick Attack stat by 6/7/8/9/10%"},
    "Date Kogyo\'s Senior": "When casting Block skills, increases Team morale by 3/3/4/4/5",
    "Silence and Sarcasm": {"Aone SP": "Block +5/7/9/12/15, Block +1/2/3/4/5%","Futakuchi SSR": ""},
    "Beach":"While allies are in Team Spirit Awakening, during a 2/3-man block, participating members' [Reaction] +6%. Effect lasts until the ball crosses the net 2 times. At rally start, allies' Team Spirit +20.",
    "Cannon and Iron Wall": {"Aone SP": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%", "Asahi SSR":""},
    "Sports Festival":"When an ally member touches the ball, consume 1 Stamina and increase that member’s main stats by 3%/3.5%/4%/4.5%/5% for 2 net crossings.If that ball touch is a block, that member’s Block increases by an additional 5% for 2 net crossings.",
    "Date Tech’s Setter":{"Kanji SP": "Set +5/7/9/12/15, Set +1/2/3/4/5%","Kaname SR": "Set +5/7/9/12/15, Set +1/2/3/4/5%"},
    "Training Camp Teammates - Youth Selection":"Ally members on the court with a block skill gain +6%/+7%/+8%/+9%/+10% Block. The cooldown of <Block System> is reduced by 2 net crossings. When an ally member activates a serve skill, inflict Enrage debuff on the opponent’s back row (Power Attack / Quick Attack –10%) for 8 net crossings.",
    "The Big Rookie and the New Captain":{"Kanji SP": "Block +5/7/9/12/15, Block +1/2/3/4/5%","Kenji SSR": "Block +5/7/9/12/15, Block +1/2/3/4/5%"},
    "The New “Iron Wall”":"When Kanji is on the court, if at least 2 members included in the Bond Skill are present, the Bond Skill becomes active. When allies perform a 2- or 3-man block, front-row allies’ Defense Technique increases by 3%/4%/5%/6%/7% for 1 rally. When an ally activates a serve skill, the serve will not fail. During rallies where an ally activates a serve skill, if allies perform a 2- or 3-man block, gain 1 stack of [Create Iron Wall].",

    //Shiratorizawa
    "Lifelong Best Friends":"Increases Ushijima\'s Attack Technique by 3/3.5/4/4.5/5% and Tendo\'s Defense Technique by 3/3.5/4/4.5/5%",
    "Promising Senpai":{"Tendo SSR":"Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%","Goshiki SSR":"Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%"},
    "Undisputed Aces":{"Goshiki SSR":"Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Ushijima UR":"Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%"},
    "Shiratorizawa\'s Middke Blocker":"Increases Block stat of your side\'s front row players by 5/5.5/6/6.5/7%",
    "Prediction VS System":{"Tsukishima SSR":"No buff","Tendo SSR":"Block +5/7/9/12/15, Block +1/2/3/4/5%"},
    "Ushiwaka and Benkei": {"Ushijima UR": "Block +5/7/9/12/15, Block +1/2/3/4/5%","Ohira SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%"},
    "The Absolute King and the Steadfast Setter": "When Shirabu sets, Ushijima performs a [Spike] with 260% of [Spike] power. Ushijima’s [Power] increases by 10% for this spike.",
    "The Absolute King VS the Freak Duo": {"Ushijima UR": "Spike +5/7/9/12/15, Spike +1/2/3/4/5%","Hinata SSR":"","Kageyama UR":""},
    "Shiratorizawa 2nd Years": {"Shirabu SSR": "Toss +5/7/9/12/15, Toss +1/2/3/4/5%","Taichi SR": "Quick +5/7/9/12/15, Quick +1/2/3/4/5%"},
    "Shiratorizawa 3rd Years": {"Ushijima UR": "","Yamagata SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Ohira SSR": "Spike +5/7/9/12/15, Spike +1/2/3/4/5%","Semi SSR": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%","Tendo SSR": "Block +5/7/9/12/15, Block +1/2/3/4/5%"},
    "Setters of Different Types": {"Shirabu SSR": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%","Semi SSR": "Toss +5/7/9/12/15, Toss +1/2/3/4/5%"},
    "Shiratorizawa's WS": "Allies’ [Spike] increases by 4%",
    "From the Great Ace to the Next Ace": {"Ushijima SP": "Power +5/7/9/12/15, Power +1/2/3/4/5%","Goshiki SSR": "Power +5/7/9/12/15, Power +1/2/3/4/5%"},
    "Ushiwaka and Benkei SP": {"Ushijima SP": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%","Ohira SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%"},
    "The Absolute King and the Steadfast Setter SP": {"Ushijima SP": "Power +5/7/9/12/15, Power +1/2/3/4/5%","Shirabu SSR": "Toss +5/7/9/12/15, Toss +1/2/3/4/5%"},
    "The Absolute King VS the Freak Duo SP": {"Ushijima SP": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%","Hinata SP":"Quick +5/7/9/12/15, Quick +1/2/3/4/5%","Kageyama UR":"Toss +5/7/9/12/15, Toss +1/2/3/4/5%"},
    "Guess vs System": {"Tsukishima SP": "Quick +5/7/9/12/15, Quick +1/2/3/4/5%","Tendo SP": "Block +5/7/9/12/15, Block +1/2/3/4/5%"},
    "Lifelong Best Friends SP": "When Ushijima receives a debuff, Tendo gains Block +4% and Speed ATK +4%. (Maximum boost: 12%) If Tendo successfully performs a Nice Play with his Block, then Ushijima’s Spike Power increases by [Power] 6/7/8/9/10%. This effect lasts for 1 rally.",
    "Expectations of a senior": {"Tendo SP": "Quick +5/7/9/12/15, Quick +1/2/3/4/5%","Goshiki SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%"},
    "Shiratorizawa\'s Middle Blocker SP": {"Tendo SP": "Quick +5/7/9/12/15, Quick +1/2/3/4/5%","Taichi SR": "Block +5/7/9/12/15, Block +1/2/3/4/5%"},
    "Shiratorizawa 3rd Years SP": {"Ushijima SP": "Block +5/7/9/12/15, Block +1/2/3/4/5%","Semi SSR": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%","Tendo SSR": "Block +5/7/9/12/15, Block +1/2/3/4/5%","Ohira SSR": "Power +5/7/9/12/15, Power +1/2/3/4/5%","Yamagata SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%"},

    //Fukurodani 
    "The Moment They Fell in Love with Volleyball": {"Bokuto UR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Tsukishima SSR":""},
    "Tokyo Training Camp Self-Practice Buddies": {"Bokuto UR": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%","Akaashi SSR": "Toss +5/7/9/12/15, Toss +1/2/3/4/5%","Kuroo UR":"","Tsukishima SSR":""},
    "Miracle Ace and the Stubborn Setter": "Bokuto loses [Slump Mode]. Akaashi sets, and Bokuto performs a [Spike] with 265% [Spike] power. For this spike, Bokuto’s [Spike] increases by 20%, and all allies’ [Morale] increases by 15.",
    "Number One Disciple": {"Bokuto UR": "Spike +5/7/9/12/15, Spike +1/2/3/4/5%", "Hinata SSR":""},
    "Fukurodani WS": {"Bokuto UR":"","Sarukui SR": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%"},
    "Fukurodani MBs": {"Washio SSR": "Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%","Onaga R":""},
    "Fukurodani 3rd Years": {"Bokuto UR": "","Komi SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Konoha SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Sarukui SR": "Power +5/7/9/12/15, Power +1/2/3/4/5%", "Washio SSR": "Block +5/7/9/12/15, Block +1/2/3/4/5%"},
    "Kizuna Skills":"Akaashi (Beach)'s [Toss] +6%. While an ally has Team Spirit activated, Bokuto (Beach)'s [Power] +18% and Akaashi (Beach)'s [Toss] gains an additional +5%.",
    "Miracle Ace & Considerate Setter": "Akaashi (Beach) Toss +6%. While teammates are in Team Spirit mode, Bokuto (Beach) gets +18% Power. Akaashi (Beach) Toss +5% more during this time.",
    "Tokyo Training Camp Buddies": {"Bokuto SP": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Akaashi SP": "Toss +5/7/9/12/15, Toss +1/2/3/4/5%","Tsukishima SP": "Block +5/7/9/12/15, Block +1/2/3/4/5%","Kuroo SP": "Block +5/7/9/12/15, Block +1/2/3/4/5%"},

    //Jozenji
    "The Value of the 'Stage'": {"Terushima SSR": "Block +5/7/9/12/15, Block +1/2/3/4/5%","Daichi SSR":""},
    "Two High-Energy Guys": { "Bobata R":"","Terushima SSR": "Attack +5/7/9/12/15, Attack +1/2/3/4/5%"},
    "Jouzenji's WS": {"Higashiyama SR": "Attack +5/7/9/12/15, Attack +1/2/3/4/5%","Terushima SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%"},

    //Inarizaki
    "Head and Core":"Atsumu: Attack Technique +3%, gains 3 stacks of [Donpishari] (Toss +2% per stack, max 10). Kita: Main Parameter +3%, gains 1 stack of [Reliable Action] (Receive +2% per stack, max 3).",
    "Youth Camp Setters":{"Kageyama UR":"Toss +5/7/9/12/15, Toss +1/2/3/4/5%","Atsumu UR":"Toss +5/7/9/12/15, Toss +1/2/3/4/5%"},
    "Strongest High School Twins":"Atsumu tosses to Osamu who performs a minus tempo Twin Quick with [Quick] ×265% power, and Osamu’s Attack Technique increases by 15% while either twin is on court; cannot be blocked",
    "Classmates":{"Suna SSR":"Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%","Osamu UR":"Block +5/7/9/12/15, Block +1/2/3/4/5%"},
    "Inarizaki's Middle Blockers":{"Suna SSR":"Block +5/7/9/12/15, Block +1/2/3/4/5%", "Oomimi SR":"Block +5/7/9/12/15, Block +1/2/3/4/5%"},
    "Third Year from Inarizaki": {"Kita SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Ojiro SSR": "Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%","Akagi SSR": "Cover +5/7/9/12/15, Cover +1/2/3/4/5%","Omimi SR": "Block +5/7/9/12/15, Block +1/2/3/4/5%"},
    "Inarizaki 2nd Years": {"Suna SSR": "Quick Spike +5/7/9/12/15, Quick Spike +1/2/3/4/5%","Ginjima SSR": "Power Spike +5/7/9/12/15, Power Spike +1/2/3/4/5%","Osamu UR": "Quick Spike +5/7/9/12/15, Quick Spike +1/2/3/4/5%","Atsumu UR":"","Kosaku R":""},
    "Japan Youth Training Camp Teammates":{"Kageyama UR": "","Atsumu UR": "Toss +5/7/9/12/15, Toss +1/2/3/4/5%","Sakusa UR": "Strong Spike +5/7/9/12/15, Strong Spike +1/2/3/4/5%","Komori UR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Hoshiumi UR": "Strong Spike +5/7/9/12/15, Strong Spike +1/2/3/4/5%"},
    "Inarizaki WS Teammates": {"Kita SSR": "Cover +5/7/9/12/15, Cover +1/2/3/4/5%","Ojiro SSR": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%","Ginjima SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Kosaku R": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%","Riseki R": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%"},

    //Kamomedai
    "Youth Training Camp": {"Hoshiumi UR": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%","Kageyama UR":""},
    "Similar Physique Teammates": {"Hinata SSR":"","Hoshiumi UR": "Power Strike +5/7/9/12/15, Power Strike +1/2/3/4/5%"},
    "Friends from Junior High": "Hoshiumi's main parameter increases by 6%. Front row allies' [Block] increases by 6%. At the start of the match, Hoshiumi gains 1 stack of [All-Rounder] and Hirugami gains 1 stack of [Solid Block].",
    "Top Spiker and Top-Class Libero": "Sakusa’s [Spike] increases by 10%, and Komori’s [Receive] increases by 10%. All allies’ [Receive] power increases by 20% of their [Receive] stat.",



};

//Lowkey just have to remeber that when a bond is create I put it here
//template: "": { category: "school| stats|deployement", activation: { scope: "starters|any", min:  } },
const synergyMeta = {
    "Karasuno":      { category: "school", activation: { scope: "starters", min: 4 } },
    "Shiratorizawa": { category: "school", activation: { scope: "starters", min: 4 } },
    "Aoba Johsai":   { category: "school", activation: { scope: "starters", min: 4 } },
    "Nekoma":        { category: "school", activation: { scope: "starters", min: 4 } },
    "Date Kogyo":    { category: "school", activation: { scope: "starters", min: 4 } },
    "Fukurodani":    { category: "school", activation: { scope: "starters", min: 4 } },
    "Jozenji":       { category: "school", activation: { scope: "starters", min: 4 } },
    "Inarizaki":     { category: "school", activation: { scope: "starters", min: 4 } },

    "Karasuno\'s Pillar":                           { category: "deployment", activation: { scope: "any", min: 2 } },
    "Flexible Aces":                                { category: "stats",      activation: { scope: "any", min: 2 } },
    "Worthy Rival":                                 { category: "stats",      activation: { scope: "any", min: 2 } },
    "Kiyoko\'s Knights":                            { category: "deployment", activation: { scope: "any", min: 2 } },
    "karasuno Senior Year":                         { category: "deployment", activation: { scope: "any", min: 3 } },
    "\"Guardian Deity\" and \"Wing Spiker\"":       { category: "deployment", activation: { scope: "any", min: 2 } },
    "\"Shield\" and \"Spear\" (practice)":          { category: "deployment", activation: { scope: "any", min: 2 } },
    "TOMODACHI(Friends!)":                          { category: "stats",      activation: { scope: "any", min: 2 } },
    "Cannon \& Iron Wall":                          { category: "stats",      activation: { scope: "any", min: 2 } },
    "Karasuno\'s sophomore":                        { category: "stats",      activation: { scope: "any", min: 3 } },
    "\"Guardian Deity\" and \"Ace\"":               { category: "deployment", activation: { scope: "any", min: 2 } },
    "Leaders Cut from the Same Cloth":              { category: "stats",      activation: { scope: "any", min: 2 } },
    "Surprising Friendship":                        { category: "stats",      activation: { scope: "any", min: 2 } },
    "Karasuno\'s Wing Spiker":                      { category: "stats",      activation: { scope: "any", min: 3 } },
    "Teammates on the Court":                       { category: "deployment", activation: { scope: "any", min: 2 } },
    "Simulated Junior Training Teamate":            { category: "stats",      activation: { scope: "any", min: 2 } },
    "Karasuno\'s Pillar(practice)":                 { category: "stats",      activation: { scope: "any", min: 2 } },
    "\"Shield\" and \"Spear\"(practice)":           { category: "deployment", activation: { scope: "any", min: 2 } },
    "Formidable Opponent":                          { category: "stats",      activation: { scope: "any", min: 2 } },
    "Bench cheer":                                  { category: "stats",      activation: { scope: "any", min: 2 } },
    "The Returning Trio":                           { category: "stats",      activation: { scope: "any", min: 3 } },
    "\"Sun\" and \"Moon\"":                         { category: "stats",      activation: { scope: "any", min: 2 } },
    "Building Team Chemistry":                      { category: "stats",      activation: { scope: "any", min: 2 } },
    "Karasuno\'s Sophomore(practice)":              { category: "deployment", activation: { scope: "any", min: 3 } },
    "Rival Friends":                                { category: "stats",      activation: { scope: "any", min: 2 } },
    "Behind the Smile":                             { category: "stats",      activation: { scope: "any", min: 2 } },
    "Master and Apprentice":                        { category: "stats",      activation: { scope: "any", min: 2 } },
    "Weird Duo":                                    { category: "deployment", activation: { scope: "any", min: 2 } },
    "The King and The Great King":                  { category: "stats",      activation: { scope: "any", min: 2 } },
    "Karasuno's Setters":                           { category: "stats",      activation: { scope: "any", min: 2 } },
    "Karasuno's Failing Grades Group":              { category: "stats",      activation: { scope: "any", min: 4 } },
    "Team's Guardians":                             { category: "stats",      activation: { scope: "any", min: 2 } },
    "Similar Builds":                               { category: "stats",      activation: { scope: "any", min: 2 } },
    "Weird Duo (Hanami)":                           { category: "deployment", activation: { scope: "any", min: 2 } },
    "Hanami":                                       { category: "deployment", activation: { scope: "any", min: 2 } },
    "Strange Friendship":                           { category: "stats",      activation: { scope: "any", min: 2 } },
    "Number One Disciple SP":                       { category: "stats",      activation: { scope: "any", min: 2 } },
    "Karasuno's Red Mark Squad (Hanami ver.)":      { category: "stats",      activation: { scope: "any", min: 4 } },
    "Protectors of Kiyoko":                         { category: "stats",      activation: { scope: "any", min: 2 } },
    "After School":                                 { category: "deployment", activation: { scope: "any", min: 2 } },
    "Karasuno Geniuses":                            { category: "deployment", activation: { scope: "any", min: 2 } },
    "Team's Guardians (After School)":              { category: "stats",      activation: { scope: "any", min: 2 } },
    "Sun vs Moon":                                  { category: "deployment", activation: { scope: "any", min: 2 } },
    "Karasuno 3rd Years":                           { category: "stats",      activation: { scope: "any", min: 3 } },
    "Karasuno's Setters":                           { category: "stats",      activation: { scope: "any", min: 2 } },
    "The Moment They Fell for Volleyball":          { category: "stats",      activation: { scope: "any", min: 2 } },
    "Fireworks Tournament":                         { category: "deployment", activation: { scope: "any", min: 2 } },

    "Aoba Johsai's Sophomore":                      { category: "stats",      activation: { scope: "any", min: 3 } },
    "Blunt and Composed":                           { category: "deployment", activation: { scope: "any", min: 2 } },
    "The Wolf Pack":                                { category: "deployment", activation: { scope: "any", min: 2 } },
    "Hidden Fire":                                  { category: "stats",      activation: { scope: "any", min: 2 } },
    "Seijoh\'s Senior Year Pillars":                { category: "deployment", activation: { scope: "any", min: 2 } },
    "The Wolf Pack(Practice)":                      { category: "deployment", activation: { scope: "any", min: 2 } },
    "Team Chemistry":                               { category: "deployment", activation: { scope: "any", min: 2 } },
    "To Greater Heights":                           { category: "stats",      activation: { scope: "any", min: 2 } },
    "Breath of Aoba":                               { category: "deployment", activation: { scope: "any", min: 2 } },
    "Merciless Trust":                              { category: "stats",      activation: { scope: "any", min: 2 } },
    "Merciless Trust(SP)":                          { category: "stats",      activation: { scope: "any", min: 2 } },
    "Fated Rivals":                                 { category: "stats",      activation: { scope: "any", min: 2 } },
    "Calm and honest":                              { category: "stats",      activation: { scope: "any", min: 2 } },
    "Toward Greater Heights":                       { category: "stats",      activation: { scope: "any", min: 2 } },
    "\"King\" and \"Great King\"":                  { category: "deployment", activation: { scope: "any", min: 2 } },
    "Rivals by Fate":                               { category: "deployment", activation: { scope: "any", min: 2 } },
    "Culture Festival":                             { category: "deployment", activation: { scope: "any", min: 2 } },
    "In Perfect Sync":                              { category: "deployment", activation: { scope: "any", min: 2 } },
    "Wolf Society":                                 { category: "stats",      activation: { scope: "any", min: 2 } },
    "Aoba Johsai Third Years":                      { category: "stats",      activation: { scope: "any", min: 4 } },
    "Aoba Johsai Wing Spikers":                     { category: "stats",      activation: { scope: "any", min: 4 } },

    "Nekoma\'s Junior":                             { category: "stats",      activation: { scope: "any", min: 3 } },
    "\"Brain\" and \"Control Tower\"":              { category: "deployment", activation: { scope: "any", min: 2 } },
    "Nekoma\'s Wing Spiker":                        { category: "deployment", activation: { scope: "any", min: 3 } },
    "Grit and Competitive":                         { category: "stats",      activation: { scope: "any", min: 2 } },
    "One-on-One Training":                          { category: "stats",      activation: { scope: "any", min: 2 } },
    "The \"Enigmatic\" Teammate":                   { category: "stats",      activation: { scope: "any", min: 2 } },
    "\"Pivot\" and \"Defensive Pivot\"":            { category: "stats",      activation: { scope: "any", min: 2 } },
    "\"Pivot\" and \"Control Tower\"":              { category: "deployment", activation: { scope: "any", min: 2 } },
    "Reliable Seniors":                             { category: "stats",      activation: { scope: "any", min: 3 } },
    "Protective Guidance":                          { category: "deployment", activation: { scope: "any", min: 2 } },
    "Perseverance and Tenacity":                    { category: "stats",      activation: { scope: "any", min: 2 } },

    "Date Kogyo\'s Captains":                       { category: "stats",      activation: { scope: "any", min: 2 } },
    "The Silent and the Snarky":                    { category: "deployment", activation: { scope: "any", min: 2 } },
    "New Captain \& Tall Rookie":                   { category: "deployment", activation: { scope: "any", min: 2 } },
    "Date Kogyo\'s Wing Spiker":                    { category: "deployment", activation: { scope: "any", min: 2 } },
    "Date Kogyo\'s Setter":                         { category: "stats",      activation: { scope: "any", min: 2 } },
    "Date Kogyo\'s Junior":                         { category: "stats",      activation: { scope: "any", min: 2 } },
    "Date Kogyo\'s Senior":                         { category: "deployment", activation: { scope: "any", min: 3 } },
    "Silence and Sarcasm":                          { category: "stats",      activation: { scope: "any", min: 2 } },
    "Beach":                                        { category: "deployment", activation: { scope: "any", min: 3 } },
    "Cannon and Iron Wall":                         { category: "stats",      activation: { scope: "any", min: 2 } },
    "Sports Festival":                              { category: "deployment", activation: { scope: "any", min: 2 } },
    "Date Tech’s Setter":                           { category: "stats",      activation: { scope: "any", min: 2 } },
    "Training Camp Teammates - Youth Selection":    { category: "deployment", activation: { scope: "any", min: 2 } },
    "The Big Rookie and the New Captain":           { category: "stats",      activation: { scope: "any", min: 2 } },
    "The New “Iron Wall”":                          { category: "deployment", activation: { scope: "any", min: 3 } },
   
    "Lifelong Best Friends":                        { category: "deployment", activation: { scope: "any", min: 2 } },
    "Promising Senpai":                             { category: "stats",      activation: { scope: "any", min: 2 } },
    "Undisputed Aces":                              { category: "stats",      activation: { scope: "any", min: 2 } },
    "Shiratorizawa\'s Middke Blocker":              { category: "deployment", activation: { scope: "any", min: 2 } },
    "Prediction VS System":                         { category: "stats",      activation: { scope: "any", min: 2 } },
    "Ushiwaka and Benkei":                          { category: "stats",      activation: { scope: "any", min: 2 } },
    "The Absolute King and the Steadfast Setter":   { category: "deployment", activation: { scope: "any", min: 2 } },
    "The Absolute King VS the Freak Duo":           { category: "stats",      activation: { scope: "any", min: 3 } },
    "Shiratorizawa 2nd Years":                      { category: "stats",      activation: { scope: "any", min: 2 } },
    "Shiratorizawa 3rd Years":                      { category: "stats",      activation: { scope: "any", min: 5 } },
    "Setters of Different Types":                   { category: "stats",      activation: { scope: "any", min: 2 } },
    "Shiratorizawa's WS":                           { category: "deployment", activation: { scope: "any", min: 2 } },
    "From the Great Ace to the Next Ace":           { category: "stats",      activation: { scope: "any", min: 2 } },
    "Ushiwaka and Benkei SP":                       { category: "stats",      activation: { scope: "any", min: 2 } },
    "The Absolute King and the Steadfast Setter SP":{ category: "stats",      activation: { scope: "any", min: 3 } },
    "The Absolute King VS the Freak Duo SP":        { category: "stats",      activation: { scope: "any", min: 2 } },
    "Guess vs System":                              { category: "stats",      activation: { scope: "any", min: 2 } },
    "Expectations of a senior":                     { category: "stats",      activation: { scope: "any", min: 2 } },
    "Lifelong Best Friends SP":                     { category: "deployment", activation: { scope: "any", min: 2 } },
    "Shiratorizawa\'s Middle Blocker SP":           { category: "stats",      activation: { scope: "any", min: 2 } },
    "Shiratorizawa 3rd Years SP":                   { category: "stats",      activation: { scope: "any", min: 2 } },

    "The Moment They Fell in Love with Volleyball": { category: "stats",      activation: { scope: "any", min: 2 } },
    "Tokyo Training Camp Self-Practice Buddies":    { category: "stats",      activation: { scope: "any", min: 4 } },
    "Miracle Ace and the Stubborn Setter":          { category: "deployment", activation: { scope: "any", min: 2 } },
    "Number One Disciple":                          { category: "stats",      activation: { scope: "any", min: 2 } },
    "Fukurodani WS":                                { category: "stats",      activation: { scope: "any", min: 2 } },
    "Fukurodani MBs":                               { category: "stats",      activation: { scope: "any", min: 2 } },
    "Fukurodani 3rd Years":                         { category: "stats",      activation: { scope: "any", min: 2 } },
    "Kizuna Skills":                                { category: "deployment", activation: { scope: "any", min: 2 } },
    "Miracle Ace & Considerate Setter":             { category: "deployment", activation: { scope: "any", min: 2 } },
    "Tokyo Training Camp Buddies":                  { category: "stats",      activation: { scope: "any", min: 4 } },
 
    "The Value of the 'Stage'":                     { category: "stats",      activation: { scope: "any", min: 2 } },
    "Two High-Energy Guys":                         { category: "stats",      activation: { scope: "any", min: 2 } },
    "Jouzenji's WS":                                { category: "stats",      activation: { scope: "any", min: 2 } },
    "Head and Core":                                { category: "deployment", activation: { scope: "any", min: 3 } },
    "Youth Camp Setters":                           { category: "stats",      activation: { scope: "any", min: 2 } },
    "Strongest High School Twins":                  { category: "deployment", activation: { scope: "any", min: 2 } },
    "Classmates":                                   { category: "stats",      activation: { scope: "any", min: 2 } },
    "Friends from Volleyball Class":                { category: "stats",      activation: { scope: "any", min: 3 } },
    "Inarizaki's Middle Blockers":                  { category: "stats",      activation: { scope: "any", min: 2 } },
    "Third Year from Inarizaki":                    { category: "stats",      activation: { scope: "any", min: 4 } },
    "Inarizaki 2nd Years":                          { category: "stats",      activation: { scope: "any", min: 5 } },
    "Japan Youth Training Camp Teammates":          { category: "stats",      activation: { scope: "any", min: 5 } },
    "Inarizaki WS Teammates":                       { category: "stats",      activation: { scope: "any", min: 5 } },
   
    "Youth Training Camp":                          { category: "stats",      activation: { scope: "any", min: 2 } },
    "Similar Physique Teammates":                   { category: "stats",      activation: { scope: "any", min: 2 } },
    "Friends from Junior High":                     { category: "deployment", activation: { scope: "any", min: 2 } },
    "Top Spiker and Top-Class Libero":              { category: "deployment", activation: { scope: "any", min: 2 } },
};

//put what player create the bond
const synergyPairs = {
    "Karasuno\'s Pillar": [["Chikara", "Daichi"]],
    "Flexible Aces": [["Hinata", "Lev"]],
    "Worthy Rival": [["Hinata", "Inuoka"]],
    "Kiyoko\'s Knights": [["Tanaka", "Nishinoya"]],
    "karasuno Senior Year": [["Sugawara","Daichi", "Asahi"]],
    "\"Guardian Deity\" and \"Wing Spiker\"": [["Nishinoya", "Asahi"]],
    "\"Shield\" and \"Spear\"": [["Tsukishima", "Tadashi"]],
    "TOMODACHI(Friends!)":[["Tanaka","Yamamoto"]],
    "Cannon \& Iron Wall":[["Asahi", "Aone"]],
    "Karasuno\'s sophomore": [["Tanaka", "Nishinoya", "Chikara"]],
    "\"Guardian Deity\" and \"Ace\"": [["Nishinoya", "Asahi"]],
    "Leaders Cut from the Same Cloth":[["Daichi", "Kuroo"]],
    "Surprising Friendship":[["Aone", "Hinata"]],
    "Karasuno\'s Wing Spiker":[["Tanaka","Asahi","Chikara"]],//verify this one later on since 3 Wspikers
    "Teammates on the Court":[["Hinata", "Kageyama"]],
    "Simulated Junior Training Teamate":[["Kanji","Tsukishima"]],
    "Karasuno\'s Pillar(practice)": [["Chikara R", "Daichi SR"]],
    "\"Shield\" and \"Spear\"(practice)": [["Tsukishima SR", "Tadashi R"]],
    "Formidable Opponent" : [["Nishinoya", "Yaku"]],
    "Bench cheer": [["Hisashi", "Kazuhito"]],
    "The Returning Trio": [["Hisashi","Kazuhito","Chikara"]],
    "\"Sun\" and \"Moon\"": [["Tsukishima", "Hinata"]],
    "Building Team Chemistry": [["Tanaka", "Kageyama"]],
    "Karasuno\'s Sophomore(practice)": [["Tanaka SR", "Nishinoya SR", "Chikara R"]],
    "Rival Friends": [["Kenma","Hinata"]],
    "Behind the Smile": [["Daichi","Kuroo"]],
    "Master and Apprentice": [["Tsukishima","Kuroo"]],
    "Weird Duo": [["Hinata","Kageyama"]],
    "The King and The Great King": [["Kageyama","Oikawa"]],//double setter
    "Karasuno's Setters": [["Kageyama","Sugawara"]],// double setter
    "Karasuno's Failing Grades Group": [["Hinata","Kageyama","Nishinoya","Tanaka"]],
    "Team's Guardians": [["Nishinoya","Yaku"]],
    "Similar Builds": [["Hinata","Hoshiumi"]],
    "Weird Duo (Hanami)": [["Hinata","Kageyama"]],
    "Hanami": [["Hinata","Kenma"]],
    "Strange Friendship": [["Hinata","Aone"]],
    "Number One Disciple SP": [["Hinata SP","Bokuto SP"]],
    "Karasuno's Red Mark Squad (Hanami ver.)": [["Hinata", "Nishinoya", "Tanaka", "Kageyama"]],
    "Protectors of Kiyoko": [["Nishinoya", "Tanaka"]],
    "After School": [["Nishinoya", "Sugawara"]],
    "Karasuno Geniuses": [["Nishinoya", "Kageyama"]],
    "Team's Guardians (After School)": [["Nishinoya", "Yaku"]],
    "Sun vs Moon": [["Hinata","Tsukishima"]],
    "Karasuno 3rd Years": [["Sugawara", "Daichi", "Asahi"]],
    "Karasuno's Setters": [["Kageyama","Sugawara"]],
    "The Moment They Fell for Volleyball":[["Bokuto","Tsukishima"]],
    "Fireworks Tournament":[["Kuroo SP","Tsukishima SP"]],

    "Aoba Johsai's Sophomore":[["Watari", "Yahaba", "Kentaro"]],
    "Blunt and Composed":[["Kindaichi", "Kunimi"]],
    "The Wolf Pack":[["Kindaichi", "Kunimi"]],
    "Hidden Fire":[["Kentaro", "Yahaba"]],
    "Seijoh\'s Senior Year Pillars":[["Matsukawa", "Hanamaki"]],
    "The Wolf Pack(Practice)":[["Iwaizumi", "Kentaro"]],
    "Team Chemistry":[["Oikawa", "Iwaizumi"]],
    "To Greater Heights":[["Oikawa", "Kindaichi"]],
    "Breath of Aoba":[["Oikawa", "Iwaizumi"]],
    "Merciless Trust":[["Oikawa","Kentaro"]],
    "Merciless Trust(SP)":[["Oikawa SP","Kentaro SSR"]],
    "Fated Rivals":[["Oikawa","Ushijima"]],
    "Calm and honest":[["Kunimi SP","Kindaichi SR"]],
    "Toward Greater Heights":[["Oikawa SP","Kindaichi SR"]],
    "\"King\" and \"Great King\"":[["Oikawa SP","Kageyama UR"]],
    "Rivals by Fate":[["Oikawa SP","Ushijima SP"]],
    "Culture Festival":[["Oikawa SP","Ushijima SP","Iwaizumi SP"]],
    "In Perfect Sync":[["Oikawa SP","Iwaizumi SP"]],
    "Wolf Society":[["Iwaizumi SP","Kentaro SSR"]],
    "Aoba Johsai Third Years":[["Iwaizumi SP","Oikawa SP","Matsukawa SR","Hanamaki SR"]],
    "Aoba Johsai Wing Spikers":[["Iwaizumi SP","Hanamaki SR","Kunimi SP","Kentaro SSR",]],

    "Nekoma\'s Junior":[["Teshiro", "Inuoka","Lev"]],
    "\"Brain\" and \"Control Tower\"":[["Kenma", "Kuroo"]],
    "Nekoma\'s Wing Spiker":[["Ifukunaga", "Kai","Yamamoto"]],
    "Grit and Competitive":[["Kenma", "Yamamoto"]],
    "One-on-One Training":[["Lev", "Yaku"]],
    "The \"Enigmatic\" Teammate":[["Kenma", "Lev"]],
    "\"Pivot\" and \"Defensive Pivot\"":[["Kenma", "Yaku"]],
    "\"Pivot\" and \"Control Tower\"":[["Kenma", "Kuroo"]],
    "Reliable Seniors":[["Kuroo","Yaku","Kai"]],
    "Protective Guidance":[["Yaku","Lev"]],
    "Perseverance and Tenacity":[["Kenma", "Yamamoto"]],

    
    "Date Kogyo\'s Captains":[["Kenji","Kaname"]],
    "The Silent and the Snarky":[["Aone","Kenji"]],
    "New Captain \& Tall Rookie":[["Kenji","Kanji"]],
    "Date Kogyo\'s Wing Spiker": [["Yutaka","Takehito"]],
    "Date Kogyo\'s Setter":[["Kanji","Kaname"]],
    "Date Kogyo\'s Junior": [["Jingo","Sakunami"]],
    "Date Kogyo\'s Senior": [["Takehito"," Kaname","Kamasaki"]],
    "Silence and Sarcasm":[["Aone (Beach)", "Futakuchi"]],
    "Beach":[["Aone", "Futakuchi", "Koganegawa"]],
    "Cannon and Iron Wall":[["Aone", "Asahi"]],
    "Sports Festival":[["Kanji", "Kunimi"]],
    "Date Tech’s Setter":[["Kanji","Kaname"]],
    "Training Camp Teammates - Youth Selection":[["Kanji","Tsukishima"]],
    "The Big Rookie and the New Captain":[["Kanji","Kenji"]],
    "The New “Iron Wall”":[["Kanji","Kenji","Aone"]],

    "Ushiwaka and Benkei":[["Ushijima","Ohira Shion"]],
    "The Absolute King and the Steadfast Setter":[["Shirabu","Ushijima"]],
    "The Absolute King VS the Freak Duo":[["Ushijima","Hinata","Kageyama"]],
    "Shiratorizawa 2nd Years":[["Shirabu","Kawanishi"]],
    "Shiratorizawa 3rd Years": [["Yamagata", "Ohira", "Semi", "Tendo", "Ushijima"]],
    "Setters of Different Types": [["Shirabu", "Semi"]],
    "Shiratorizawa's WS": [["Ohira", "Goshiki"]],
    "From the Great Ace to the Next Ace":[["Ushijima SP","Goshiki SSR"]],
    "Ushiwaka and Benkei SP":[["Ushijima SP","Ohira SSR"]],
    "The Absolute King and the Steadfast Setter SP":[["Shirabu","Ushijima"]],
    "The Absolute King VS the Freak Duo SP":[["Ushijima SP","Hinata SP","Kageyama UR"]],
    "Guess vs System": [["Tendo SP", "Tsukishima SP"]],
    "Expectations of a senior": [["Tendo SP", "Goshiki SSR"]],
    "Lifelong Best Friends SP":[["Tendo SP", "Ushijima SP"]],
    "Shiratorizawa\'s Middle Blocker SP":[["Tendo SP", "Taichi SR"]],
    "Shiratorizawa 3rd Years SP": [["Ushijima SP","Semi SSR","Tendo SP","Ohira SSR","Yamagata SSR"]],

    "The Moment They Fell in Love with Volleyball": [["Bokuto", "Tsukishima"]],
    "Tokyo Training Camp Self-Practice Buddies": [["Bokuto", "Kuroo", "Akaashi", "Tsukishima"]],
    "Miracle Ace and the Stubborn Setter": [["Bokuto", "Akaashi"]],
    "Number One Disciple": [["Bokuto", "Hinata"]],
    "Fukurodani WS": [["Bokuto", "Sarukui"]],
    "Fukurodani MBs":[["Onaga","Washio"]],
    "Fukurodani 3rd Years": [["Bokuto", "Komi", "Konoha", "Sarukui", "Washio"]],
    "Kizuna Skills":[["Bokuto","Akaashi"]],
    "Miracle Ace & Considerate Setter": [["Bokuto", "Akaashi"]],
    "Tokyo Training Camp Buddies": [["Bokuto", "Akaashi", "Tsukishima", "Kuroo"]],

    "The Value of the 'Stage'": [["Daichi","Terushima"]],
    "Two High-Energy Guys": [["Bobata","Terushima"]],
    "Jouzenji's WS": [["Higashiyama","Terushima"]],

    "Head and Core":[["Kita","Atsumu","Osamu"]],
    "Youth Camp Setters":[["Kageyama","Atsumu"]],
    "Strongest High School Twins":[["Atsumu","Osamu"]],
    "Classmates":[["Suna","Osamu"]],
    "Friends from Volleyball Class":[["Atsumu","Osamu","Ojiro"]],
    "Inarizaki's Middle Blockers":[["Suna","Omimi"]],
    "Third Year from Inarizaki":[["Kita","Akagi","Ojiro","Omimi"]],
    "Inarizaki 2nd Years":[["Suna","Kosaku","Atsumu","Osamu","Ginjuma"]],
    "Japan Youth Training Camp Teammates":[["Kageyama","Sakusa","Atsumu","Komori","Hoshiumi"]],
    "Inarizaki WS Teammates":[["Kita","Ojiro","Ginjima","Kosaku","Riseki"]],

    "Youth Training Camp":[["Kageyama","Hoshiumi"]],
    "Similar Physique Teammates":[["Hinata","Hoshiumi"]],
    "Friends from Junior High":[["Hirugami","Hoshiumi"]],
    "Top Spiker and Top-Class Libero":[["Komori","Sakusa"]],
};

window.characters = characters;
window.synergyDescriptions = synergyDescriptions;
window.synergyMeta = synergyMeta;
window.synergyPairs = synergyPairs;