// template: { name: "", role: "", img: "img-global/", school: "", bonds: [] },
const characters = [
    { name: "Hinata SSR", role: "MB", img: "img-global/hinataSSR.png", school: "Karasuno", bonds: ["Flexible Aces", "Worthy Rival", "Surprising Friendship", "Rival Friends", "Top Disciple","Little Giants"] },
    { name: "Hinata SR", role: "MB", img: "img-global/hinataSR.png", school: "Karasuno", bonds: ["Teammates on the Court", "\"Sun\" and \"Moon\""] },
    { name: "Kageyama SSR", role: "S", img: "img-global/tobioSSR.png", school: "Karasuno", bonds: ["Teammates on the Court", "Building Team Chemistry"] },
    { name: "Daichi SSR", role: "OP", img: "img-global/daichiSSR.png", school: "Karasuno", bonds: ["Karasuno\'s Pillar", "karasuno Senior Year", "Behind the Smile"] },
    { name: "Daichi SR", role: "OP", img: "img-global/daichiSR.png", school: "Karasuno", bonds: ["Karasuno\'s Pillar(practice)", "Leaders Cut from the Same Cloth"] },
    { name: "Sugawara SR", role: "S", img: "img-global/sugawaraSR.png", school: "Karasuno", bonds: ["karasuno Senior Year",] },
    { name: "Asahi SSR", role: "WS", img: "img-global/asahiSSR.png", school: "Karasuno", bonds: ["karasuno Senior Year", "\"Guardian Deity\" and \"Wing Spiker\"", "Cannon \& Iron Wall"] },
    { name: "Asahi SR", role: "WS", img: "img-global/asahiSR.png", school: "Karasuno", bonds: ["\"Guardian Deity\" and \"Ace\"", "Karasuno\'s Wing Spiker"] },
    { name: "Nishinoya SSR", role: "Li", img: "img-global/nishinoyaSSR.png", school: "Karasuno", bonds: ["Karasuno\'s sophomore", "Kiyoko\'s Knights", "\"Guardian Deity\" and \"Wing Spiker\""] },
    { name: "Nishinoya SR", role: "Li", img: "img-global/nishinoyaSR.png", school: "Karasuno", bonds: ["\"Guardian Deity\" and \"Ace\"", "Formidable Opponent", "Karasuno\'s Sophomore(practice)"] },
    { name: "Tanaka SSR", role: "WS", img: "img-global/tanakaSSR.png", school: "Karasuno", bonds: ["Karasuno\'s sophomore", "Kiyoko\'s Knights", "TOMODACHI(Friends!)"] },
    { name: "Tanaka SR", role: "WS", img: "img-global/tanakaSR.png", school: "Karasuno", bonds: ["Karasuno\'s Wing Spiker", "Building Team Chemistry", "Karasuno\'s Sophomore(practice)"] },
    { name: "Tsukishima SSR", role: "MB", img: "img-global/tsukishimaSSR.png", school: "Karasuno", bonds: ["The Moment you'll be hooked on volleyball","\"Shield\" and \"Spear\"", "Master and Apprentice", "Prediction VS System","Tokyo Camp Training Partners"] },
    { name: "Tsukishima SR", role: "MB", img: "img-global/tsukishimaSR.png", school: "Karasuno", bonds: ["Simulated Junior Training Teamate", "\"Shield\" and \"Spear\"(practice)", "\"Sun\" and \"Moon\""] },
    { name: "Tadashi SR", role: "MB", img: "img-global/tadashiSR.png", school: "Karasuno", bonds: ["\"Shield\" and \"Spear\"",] },
    { name: "Tadashi R", role: "MB", img: "img-global/tadashiR.png", school: "Karasuno", bonds: ["\"Shield\" and \"Spear\"(practice)"] },
    { name: "Chikara SR", role: "WS", img: "img-global/chikaraSR.png", school: "Karasuno", bonds: ["Karasuno\'s sophomore", "Karasuno\'s Pillar", "The Returning Trio"] },
    { name: "Chikara R", role: "WS", img: "img-global/chikaraR.png", school: "Karasuno", bonds: ["Karasuno\'s Wing Spiker", "Karasuno\'s Pillar(practice)", "Karasuno\'s Sophomore(practice)"] },
    { name: "Hisashi R", role: "WS", img: "img-global/hisashiR.png", school: "Karasuno", bonds: ["Bench cheer", "The Returning Trio"] },
    { name: "Kazuhito R", role: "MB", img: "img-global/kazuhitoR.png", school: "Karasuno", bonds: ["Bench cheer", "The Returning Trio"] },
    { name: "Kageyama SR", role: "S", img: "img-global/tobioSR.png", school: "Kitagawa", bonds: [] },

    { name: "Oikawa UR", role: "S", img: "img-global/oikawaUR.png", school: "Aoba Johsai", bonds: ["Breath of Aoba", "To Greater Heights", "Fated Rivals", "Merciless Trust"] },
    { name: "Oikawa SSR", role: "S", img: "img-global/oikawaSSR.png", school: "Aoba Johsai", bonds: ["Team Chemistry"] },
    { name: "Iwaizumi SSR", role: "WS", img: "img-global/iwaizumiSSR.png", school: "Aoba Johsai", bonds: ["The Wolf Pack", "Breath of Aoba"] },
    { name: "Iwaizumi SR", role: "WS", img: "img-global/iwaizumiSR.png", school: "Aoba Johsai", bonds: ["The Wolf Pack(Practice)", "Team Chemistry"] },
    { name: "Matsukawa SR", role: "MB", img: "img-global/matsukawaSR.png", school: "Aoba Johsai", bonds: ["Seijoh\'s Senior Year Pillars"] },
    { name: "Hanamaki SR", role: "WS", img: "img-global/hanamakiSR.png", school: "Aoba Johsai", bonds: ["Seijoh\'s Senior Year Pillars"] },
    { name: "Yahaba SR", role: "S", img: "img-global/yahabaSR.png", school: "Aoba Johsai", bonds: ["Aoba Johsai's Sophomore", "Hidden Fire"] },
    { name: "Watari SR", role: "Li", img: "img-global/watariSR.png", school: "Aoba Johsai", bonds: ["Aoba Johsai's Sophomore"] },
    { name: "Kindaichi SR", role: "MB", img: "img-global/kindaichiSR.png", school: "Aoba Johsai", bonds: ["Blunt and Composed", "To Greater Heights"] },
    { name: "Kunimi SR", role: "OP", img: "img-global/kunimiSR.png", school: "Aoba Johsai", bonds: ["Blunt and Composed"] },
    { name: "Kentaro SSR", role: "OP", img: "img-global/kyotaniSSR.png", school: "Aoba Johsai", bonds: ["Aoba Johsai's Sophomore", "Hidden Fire", "The Wolf Pack", "Merciless Trust"] },
    { name: "Kentaro SR", role: "OP", img: "img-global/kyotaniSR.png", school: "Aoba Johsai", bonds: ["The Wolf Pack(Practice)"] },

    { name: "Kenma SSR", role: "S", img: "img-global/kenmaSSR.png", school: "Nekoma", bonds: ["Rival Friends", "\"Brain\" and \"Control Tower\"", "Grit and Competitive", "The \"Enigmatic\" Teammate"] },
    { name: "Kenma SR", role: "S", img: "img-global/kenmaSR.png", school: "Nekoma", bonds: ["\"Pivot\" and \"Defensive Pivot\"", "\"Pivot\" and \"Control Tower\""] },
    { name: "Kuroo UR", role: "MB", img: "img-global/kurooUR.png", school: "Nekoma", bonds: ["Behind the Smile", "Master and Apprentice", "\"Brain\" and \"Control Tower\"","Tokyo Camp Training Partners"] },
    { name: "Kuroo SSR", role: "MB", img: "img-global/kurooSSR.png", school: "Nekoma", bonds: ["Leaders Cut from the Same Cloth", "\"Pivot\" and \"Control Tower\""] },
    { name: "Yaku SR", role: "Li", img: "img-global/yakuSR.png", school: "Nekoma", bonds: ["Formidable Opponent", "One-on-One Training", "\"Pivot\" and \"Defensive Pivot\""] },
    { name: "Lev SSR", role: "MB", img: "img-global/levSSR.png", school: "Nekoma", bonds: ["Flexible Aces", "Nekoma\'s Junior", "The \"Enigmatic\" Teammate", "Protective Guidance"] },
    { name: "Lev SR", role: "MB", img: "img-global/levSR.png", school: "Nekoma", bonds: ["One-on-One Training"] },
    { name: "Yamamoto SR", role: "WS", img: "img-global/yamamotoSR.png", school: "Nekoma", bonds: ["TOMODACHI(Friends!)", "Nekoma\'s Wing Spiker", "Grit and Competitive"] },
    { name: "Kai SR", role: "OP", img: "img-global/kaiSR.png", school: "Nekoma", bonds: ["Nekoma\'s Wing Spiker"] },
    { name: "Fukunaga SR", role: "WS", img: "img-global/fukunagaSR.png", school: "Nekoma", bonds: ["Nekoma\'s Wing Spiker"] },
    { name: "Inuoka SR", role: "MB", img: "img-global/inuokaSR.png", school: "Nekoma", bonds: ["Worthy Rival", "Nekoma\'s Junior"] },
    { name: "Teshiro SR", role: "S", img: "img-global/teshiroSR.png", school: "Nekoma", bonds: ["Nekoma\'s Junior"] },
    { name: "Yaku SSR", role: "Li", img: "img-global/yakuSSR.png", school: "Nekoma", bonds: ["Team's Guardians", "Reliable Seniors", "Protective Guidance"] },


    { name: "Aone SSR", role: "MB", img: "img-global/aoneSSR.png", school: "Date Kogyo", bonds: ["Cannon \& Iron Wall", "Surprising Friendship", "The Silent and the Snarky"] },
    { name: "Aone SR", role: "MB", img: "img-global/aoneSR.png", school: "Date Kogyo", bonds: [] },
    { name: "Kenji SSR", role: "WS", img: "img-global/kenjiSSR.png", school: "Date Kogyo", bonds: ["Date Kogyo\'s Captains", "The Silent and the Snarky", "New Captain \& Tall Rookie"] },
    { name: "Kenji SR", role: "WS", img: "img-global/kenjiSR.png", school: "Date Kogyo", bonds: [] },
    { name: "Kanji SSR", role: "S", img: "img-global/kanjiSSR.png", school: "Date Kogyo", bonds: ["New Captain \& Tall Rookie", "Date Kogyo\'s Setter",] },
    { name: "Kanji SR", role: "S", img: "img-global/kanjiSR.png", school: "Date Kogyo", bonds: ["Simulated Junior Training Teamate"] },
    { name: "Sakunami R", role: "Li", img: "img-global/sakunamiR.png", school: "Date Kogyo", bonds: ["Date Kogyo\'s Junior"] },
    { name: "Kamasaki SR", role: "MB", img: "img-global/kamasakiSR.png", school: "Date Kogyo", bonds: ["Date Kogyo\'s Senior"] },
    { name: "Kaname SR", role: "S", img: "img-global/kanameSR.png", school: "Date Kogyo", bonds: ["Date Kogyo\'s Captains", "Date Kogyo\'s Setter", "Date Kogyo\'s Senior",] },
    { name: "Sasaya SSR", role: "OP", img: "img-global/takehitoSSR.png", school: "Date Kogyo", bonds: ["Date Kogyo\'s Wing Spiker", "Date Kogyo\'s Senior"] },
    { name: "Sasaya SR", role: "OP", img: "img-global/takehitoSR.png", school: "Date Kogyo", bonds: [] },
    { name: "Yutaka SR", role: "WS", img: "img-global/yutakaSR.png", school: "Date Kogyo", bonds: ["Date Kogyo\'s Wing Spiker"] },
    { name: "Jingo R", role: "MB", img: "img-global/jingoR.png", school: "Date Kogyo", bonds: ["Date Kogyo\'s Junior"] },
    { name: "Taro R", role: "OP", img: "img-global/taroR.png", school: "Date Kogyo", bonds: [] },

    { name: "Ushijima UR", role: "OP", img: "img-global/ushijimaUR.png", school: "Shiratorizawa", bonds: ["Undisputed Ace and Shadow Setter","Lifelong Best Friends", "Undisputed Aces", "Undisputed Ace and Shadow Setter", "Shiratorizawa's Senior", "Fated Rivals", "Ushiwaka and Benkei", "The Absolute King and the Steadfast Setter"] },
    { name: "Goshiki SSR", role: "WS", img: "img-global/goshikiSSR.png", school: "Shiratorizawa", bonds: ["Promising Senpai", "Undisputed Aces", "Shiratorizawa's WS"] },
    { name: "Tendo SSR", role: "MB", img: "img-global/tendoSSR.png", school: "Shiratorizawa", bonds: ["Shiratorizawa's Senior", "Lifelong Best Friends", "Promising Senpai", "Shiratorizawa\'s Middke Blocker", "Prediction VS System"] },
    { name: "Taichi SR", role: "MB", img: "img-global/kawanishiSR.png", school: "Shiratorizawa", bonds: ["Shiratorizawa\'s Middke Blocker", "Shiratorizawa 2nd Years"] },
    { name: "Shirabu SSR", role: "S", img: "img-global/shirabuSSR.png", school: "Shiratorizawa", bonds: ["Contrasting Setters","Undisputed Ace and Shadow Setter","The Absolute King and the Steadfast Setter", "Shiratorizawa 2nd Years"] },
    { name: "Semi SSR", role: "S", img: "img-global/semiSSR.png", school: "Shiratorizawa", bonds: ["Contrasting Setters", "Shiratorizawa's Senior", "Setters of Different Types"] },
    { name: "Ohira SSR", role: "WS", img: "img-global/ohiraSSR.png", school: "Shiratorizawa", bonds: ["Shiratorizawa's Senior", "Ushiwaka and Benkei", "Shiratorizawa's WS"] },
    { name: "Yamagata SSR", role: "Li", img: "img-global/yamagataSSR.png", school: "Shiratorizawa", bonds: ["Shiratorizawa's Senior"] },

    { name: "Bokuto UR", role: "WS", img: "img-global/bokutoUR.png", school: "Fukurodani", bonds: ["Miracle Ace and Attentive Setter","Top Disciple","The Moment you'll be hooked on volleyball","Fukurodani's Wing Spiker","Tokyo Camp Training Partners"] },
    { name: "Akaashi SSR", role: "S", img: "img-global/akaashiSSR.png",school: "Fukurodani", bonds: ["Miracle Ace and Attentive Setter","Tokyo Camp Training Partners"] },
    { name: "Konoha SSR",role: "OP", img: "img-japan/konohaSSR.png",school: "Fukurodani",bonds: ["Fukurodani 3rd Years"] },
    { name: "Sarukui SR", role: "WS", img: "img-global/sarukuiSR.png",school: "Fukurodani", bonds: ["Fukurodani's Wing Spiker","Fukurodani 3rd Years"] },
    { name: "Komi SSR",role: "Li", img: "img-japan/komiSSR.png",school: "Fukurodani",bonds: ["Fukurodani 3rd Years"] },
    { name: "Onaga R", role: "MB", img: "img-global/onagaR.png",school: "Fukurodani", bonds: ["Fukurodani MBs"] },
    { name: "Washio SSR",role: "MB", img: "img-japan/washioSSR.png",school: "Fukurodani",bonds: ["Fukurodani MBs","Fukurodani 3rd Years"] },

    { name: "Atsumu UR",      role: "S",  img: "img-global/atsumuUR.png",      /*power:"Quick",*/                     school: "Inarizaki",     bonds: ["Head and Core",,"Strongest High School Twins","Friends from Volleyball Class","Inarizaki 2nd Years",] },
    { name: "Osamu UR",       role: "OP", img: "img-global/osamuUR.png",       /*power:"Quick",*/                     school: "Inarizaki",     bonds: ["Head and Core","Strongest High School Twins","Classmates","Friends from Volleyball Class","Inarizaki 2nd Years"] },
    { name: "Kita SSR",       role: "WS", img: "img-global/kitaSSR.png",       /*power:"Receive",*/                   school: "Inarizaki",     bonds: ["Head and Core","Third Year from Inarizaki","Inarizaki WS Teammates"] },
    { name: "Suna SSR",       role: "MB", img: "img-global/sunaSSR.png",       /*power:["Block","Quick"],*/           school: "Inarizaki",     bonds: ["Classmates","Inarizaki's Middle Blockers","Inarizaki 2nd Years"] },
    { name: "Ojiro SSR",      role: "WS", img: "img-global/ojiroSSR.png",      /*power:"Power",*/                     school: "Inarizaki",     bonds: ["Friends from Volleyball Class","Third Year from Inarizaki","Inarizaki WS Teammates"] },
    { name: "Akagi SSR",      role: "Li", img: "img-global/akagiSSR.png",      /*power:"Receive",*/                   school: "Inarizaki",     bonds: ["Third Year from Inarizaki",] },
    { name: "Ginjima SSR",    role: "WS", img: "img-global/ginjimaSSR.png",    /*power:["Receive","Power"],*/         school: "Inarizaki",     bonds: ["Inarizaki 2nd Years","Inarizaki WS Teammates"] },
    { name: "Omimi SR",       role: "MB", img: "img-global/omimiSR.png",       /*power:"Block",*/                     school: "Inarizaki",     bonds: ["Inarizaki's Middle Blockers","Third Year from Inarizaki"] },
    { name: "Kosaku R",       role: "WS", img: "img-global/kosakuR.png",       /*power:"Receive",*/                   school: "Inarizaki",     bonds: ["Inarizaki 2nd Years","Inarizaki WS Teammates"] },
    { name: "Riseki R",       role: "WS", img: "img-global/risekiR.png",       /*power:"Power",*/                     school: "Inarizaki",     bonds: ["Inarizaki WS Teammates"] },
    
    { name: "Hoshiumi UR",    role: "WS", img: "img-global/hoshiumiUR.png",school: "Kamomedai", bonds: ["Little Giants","Friends from Junior High"] },
    { name: "Hirugami UR",    role: "MB", img: "img-global/hirugamiUR.png",school: "Kamomedai", bonds: ["Friends from Junior High"] },
    
    { name: "Sakusa UR",      role: "WS", img: "img-global/sakusaUR.png",school: "Itachiyama", bonds: ["Japan Youth Training Camp Teammates","Top Spiker and Top-Class Libero"] },
    { name: "Komori UR",      role: "Li", img: "img-japan/komoriUR.png",school: "Itachiyama", bonds: ["Japan Youth Training Camp Teammates","Top Spiker and Top-Class Libero"] },

];
// tempalte: "": "",
const synergyDescriptions = {
    "Karasuno": "Increases Power Attack and Quick Attack stats of all players present by 10%",
    "Shiratorizawa": "Increases Awareness and Strength of all players present by 10%",
    "Aoba Johsai": "Increases Power Attack stats of all players present by 15%",
    "Nekoma": "Increases Receive stat of all players present by 15%",
    "Date Kogyo": "Increases Block stat of all players present by 15%",
    "Fukurodani":"Your Team Morale increases by 20 at the start of the match",
    "Johsenji":"All players on your side gain 2 stacks of \"Play Hard\"",
    "Inarizaki":"Increases Attack Technique and Defense Technique of all players on the court by 5%",

    //karasuno bond
    "Karasuno\'s Pillar": "When achieving a PERFECT receive, increases Team Morale by 3/3/4/4/5",
    "Flexible Aces": { "Hinata SSR": "Block +5/7/9/12/15, Block +1/2/3/4/5%", "Lev SSR": "Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%" },
    "Worthy Rival": { "Hinata SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%", "Inuoka SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%" },
    "Kiyoko\'s Knights": "When scoring, increases Team morale by 6/7/8/9/10",
    "karasuno Senior Year": "Reduces Stamina consumption of Spike skills by 10%; when performing Power Spikes, increases this player\'s Attack Technique by 6/7/8/9/10%",
    "\"Guardian Deity\" and \"Wing Spiker\"": "When Nishinoya or Asahi casts a skill, increases their Attack Technique and Defense Technique by 6/7/8/9/10%",
    "\"Shield\" and \"Spear\"": "Increases Tsukishima\'s Block stat by 6/7/8/9/10% and Tadashi\'s Serve stat by 6/7/8/9/10%",
    "TOMODACHI(Friends!)": { "Yamamoto SR": "Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%", "Tanaka SSR": "Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%" },
    "Cannon \& Iron Wall": { "Asahi SSR": "Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%", "Aone SSR": "No buff" },
    "Karasuno\'s sophomore": { "Chikara SR": "Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%", "Nishinoya SSR": "Set +5/7/9/12/15, Set +1/2/3/4/5%", "Tanaka SSR": "Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%" },
    "\"Guardian Deity\" and \"Ace\"": "When Nishinoya or Asahi casts a skill, increases their Attack Technique by 6/7/8/9/10%",
    "Leaders Cut from the Same Cloth": { "Daichi SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%", "Kuroo SSR": "Block +5/7/9/12/15, Block +1/2/3/4/5%" },
    "Surprising Friendship": { "Aone SSR": "Block +5/7/9/12/15, Block +1/2/3/4/5%", "Hinata SSR": "No buff" },
    "Karasuno\'s Wing Spiker": { "Tanaka SR": "Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%", "Asahi SR": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%", "Chikara SR": "Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%" },
    "Teammates on the Court": "When casting Quick Spike skills, increases this player's Awareness ny 6/7/8/9/10%",
    "Simulated Junior Training Teamate": { "Kanji SR": "Set +5/7/9/12/15, Set +1/2/3/4/5%", "Tsukishima SR": "No buff" },
    "Karasuno\'s Pillar(practice)": { "Chikara R": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%", "Daichi SR": "Block +5/7/9/12/15, Block +1/2/3/4/5%" },
    "\"Shield\" and \"Spear\"(practice)": "Increases Tsukishima\'s Block stat by 6/7/8/9/10% and Tadashi\'s Serve stat by 6/7/8/9/10%",
    "Formidable Opponent": { "Nishinoya SR": " Save +5/7/9/12/15, Save +1/2/3/4/5%", "Yaku SR": " Set +5/7/9/12/15, Set +1/2/3/4/5%" },
    "Bench cheer": { "Hisashi R": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%", "Kazuhito R": "Block +5/7/9/12/15, Block +1/2/3/4/5%" },
    "The Returning Trio": { "Hisashi R": "Set +5/7/9/12/15, Set +1/2/3/4/5%", "Kazuhito R": "Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%", "Chikara SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%" },
    "\"Sun\" and \"Moon\"": { "Tsukishima SR": "Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%", "Hinata SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%" },
    "Building Team Chemistry": { "Kageyama SSR": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%", "Tanaka SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%" },
    "Karasuno\'s Sophomore(practice)": "Increases Receive stat of back row players 6/7/8/9/10%",
    "Rival Friends": { "Hinata SSR": "Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%", "Kenma SSR": "Set +5/7/9/12/15, Set +1/2/3/4/5%" },
    "Behind the Smile": { "Daichi SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%", "Kuroo UR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%" },
    "Master and Apprentice": { "Tsukishima SSR": "Block +5/7/9/12/15, Block +1/2/3/4/5%", "Kuroo UR": "Block +5/7/9/12/15, Block +1/2/3/4/5%" },
    "Team's Guardians": { "Nishinoya SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%", "Yaku SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%" },


    //Aoba Johsai
    "Aoba Johsai's Sophomore": { "Watari SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%", "Yahaba SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%", "Kentaro SSR": "No buff" },
    "Blunt and Composed": "Increases Kindaichi\'s Quick Attack stat by 6/7/8/9/10% and  Kunimi\'s Power Attack stat by 6/7/8/9/10%",
    "The Wolf Pack": "Increases  Iwaizumi and Kentaro\'s Power Attack stat by 6/7/8/9/10%",
    "Hidden Fire": { "Kentaro SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%", "Yahaba SR": "No buff" },
    "Seijoh\'s Senior Year Pillars": "Increases Matsukawa\'s Block stat by 6/67/8/9/10% and Hanamaki\'s Receive stat by 6/7/8/9/10%",
    "The Wolf Pack(Practice)": "Increases Iwaisumi and Kentaro's Awareness by 6/7/8/9/10%",
    "Team Chemistry": "Increases Oikawa and Iwaizumi's Awareness by 6/7/8/9/10%",
    "To Greater Heights": { "Kindaichi SR": "", "Oikawa UR": "Toss +5/7/9/12/15, Toss +1/2/3/4/5%" },
    "Breath of Aoba": "When Oikawa performs a toss, Iwaizumi performs a Spike with 255% Attack power. Gains 2 stacks of [Attack Rhythm]. For each stack of [Attack Rhythm], all allies' Awareness increases by 1%. Max 10 stacks.",
    "Merciless Trust": { "Kentaro SSR": "Spike +5/7/9/12/15, Spike +1/2/3/4/5%", "Oikawa UR": "Block +5/7/9/12/15, Block +1/2/3/4/5%" },
    "Fated Rivals": { "Oikawa UR": "Toss +5/7/9/12/15, Toss +1/2/3/4/5%", "Ushijima UR": "" },


    //Nekoma
    "Nekoma\'s Junior": { "Teshiro SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%", "Inuoka SR": "No buff", "Lev SSR": "No Buff" },
    "\"Brain\" and \"Control Tower\"": "Kenma sets the ball, Kuroo performs a Quick Spike with 265/280/295/310/325% of Quick Attack stat as power",
    "Nekoma\'s Wing Spiker": "Increases Receive and Power Attack stats of players present by 4/5/6/7/8%",
    "Grit and Competitive": { "Yamamoto SR": "No buff", "Kenma SSR": "Set +5/7/9/12/15, Set +1/2/3/4/5%" },
    "One-on-One Training": { "Lev SR": "Block +5/7/9/12/15, Block +1/2/3/4/5%", "Yaku SR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%" },
    "The \"Enigmatic\" Teammate": { "Lev SSR": "Block +5/7/9/12/15, Block +1/2/3/4/5%", "Kenma SSR": "No buff" },
    "\"Pivot\" and \"Defensive Pivot\"": { "Yaku SR": "Save +5/7/9/12/15, Save +1/2/3/4/5%", "Kenma SSR": "Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%" },
    "\"Pivot\" and \"Control Tower\"": "Increases Kenma\'s Set stat by 6/7/8/9/10% and Kuroo\'s Block Stat by 6/7/8/9/10%",
    "Reliable Seniors": { "Kuroo UR": "Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%", "Yaku SSR": "", "Kai SR": "" },
    "Protective Guidance": "increases Yaku receive by 6% and Lev Quick Attack by 6%",

    //Date Kogyo
    "Date Kogyo\'s Captains": { "Kaname SR": "No buff", "Kenji SSR": "Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%" },
    "The Silent and the Snarky": "Aone and Kenji perform a Double block with 180/195/210/225/240% of Aone\'s Block stat as power;applies \"Enrage\" Debuff to opponent spiker \(reduces Power\/Quick Attack stats by 10%\)",
    "New Captain \& Tall Rookie": "Increases Block stat of front row players by 2/2.5/3/3.5/4%",
    "Date Kogyo\'s Wing Spiker": "Increases Yutaka\'s Block stat by 2/2.5/3/3.5/4% and Takehito\'s Power Attack stat by 2/2.5/3/3.5/4%",
    "Date Kogyo\'s Setter": { "KanameSR": "No buff", "Kaji SSR": "Set +5/7/9/12/15, Set +1/2/3/4/5%" },
    "Date Kogyo\'s Junior": { "Jingo R": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%", "Sakunami R": "Quick Attack +5/7/9/12/15, Quick Attack stat by 6/7/8/9/10%" },
    "Date Kogyo\'s Senior": "When casting Block skills, increases Team morale by 3/3/4/4/5",

    //Shiratorizawa
    "Lifelong Best Friends": "Increases Ushijima\'s Attack Technique by 3/3.5/4/4.5/5% and Tendo\'s Defense Technique by 3/3.5/4/4.5/5%",
    "Promising Senpai": { "Tendo SSR": "Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%", "Goshiki SSR": "Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%" },
    "Undisputed Aces": { "Goshiki SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%", "Ushijima UR": "Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%" },
    "Undisputed Ace and Shadow Setter": "KENJIRO SHIRABU sets the ball, and WAKATOSHI USHIJIMA performs a Power Spike with 260/275/290/305/320% of Power Attack stat as power; for this Spike, USHIJIMA's Strength increases by 10%",
    "Shiratorizawa's Senior": { "Ushijima UR": "", "Yamagata SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%", "Ohira SSR": "Spike +5/7/9/12/15, Spike +1/2/3/4/5%", "Semi SSR": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%", "Tendo SSR": "Block +5/7/9/12/15, Block +1/2/3/4/5%" },
    "Shiratorizawa\'s Middke Blocker": "Increases Block stat of your side\'s front row players by 5/5.5/6/6.5/7%",
    "Prediction VS System": { "Tsukishima SSR": "No buff", "Tendo SSR": "Block +5/7/9/12/15, Block +1/2/3/4/5%" },
    "Ushiwaka and Benkei": { "Ushijima UR": "Block +5/7/9/12/15, Block +1/2/3/4/5%", "Ohira SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%" },
    "The Absolute King and the Steadfast Setter": "When Shirabu sets, Ushijima performs a [Spike] with 260% of [Spike] power. Ushijima’s [Power] increases by 10% for this spike.",
    "Shiratorizawa 2nd Years": { "Shirabu SSR": "Toss +5/7/9/12/15, Toss +1/2/3/4/5%", "Taichi SR": "Quick +5/7/9/12/15, Quick +1/2/3/4/5%" },
    "Shiratorizawa's WS": "Allies’ [Spike] increases by 4%",
    "Contrasting Setters":{"Shirabu SSR": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%","Semi SSR": "Toss +5/7/9/12/15, Toss +1/2/3/4/5%"},

    //fukurodani
    "Top Disciple": { "Bokuto UR": "Spike +5/7/9/12/15, Spike +1/2/3/4/5%", "Hinata SSR": "" },
    "The Moment you'll be hooked on volleyball": {"Bokuto SP": "Spikes +5/7/9/12/15, Spikes +1/2/3/4/5%","Tsukishima SP": "Quick +5/7/9/12/15, Quick +1/2/3/4/5%"},
    "Fukurodani's Wing Spiker": {"Bokuto UR":"","Sarukui SR": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%"},
    "Fukurodani MBs": {"Washio SSR": "Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%","Onaga R":""},
    "Fukurodani 3rd Years": {"Bokuto UR": "","Komi SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Konoha SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Sarukui SR": "Power +5/7/9/12/15, Power +1/2/3/4/5%", "Washio SSR": "Block +5/7/9/12/15, Block +1/2/3/4/5%"},

    "Miracle Ace and Attentive Setter": "KOTARO BOKUTO exits the [Down Mode] state. KEIJI AKAASHI sets the ball, and BOKUTO performs a Power Spike with 265/280/295/310/325% of his Power Attack stat. For this Spike, BOKUTO’s Power Attack stat increases by 20%, and your Team Morale increases by 15.",
    "Tokyo Camp Training Partners": {"Bokuto SP": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Akaashi SP": "Toss +5/7/9/12/15, Toss +1/2/3/4/5%","Tsukishima SP": "Block +5/7/9/12/15, Block +1/2/3/4/5%","Kuroo SP": "Block +5/7/9/12/15, Block +1/2/3/4/5%"},

    //inarizaki
    "Head and Core":"Atsumu: Attack Technique +3%, gains 3 stacks of [Donpishari] (Toss +2% per stack, max 10). Kita: Main Parameter +3%, gains 1 stack of [Reliable Action] (Receive +2% per stack, max 3).",
    "Youth Camp Setters":{"Kageyama UR":"Toss +5/7/9/12/15, Toss +1/2/3/4/5%","Atsumu UR":"Toss +5/7/9/12/15, Toss +1/2/3/4/5%"},
    "Strongest High School Twins":"Atsumu tosses to Osamu who performs a minus tempo Twin Quick with [Quick] ×265% power, and Osamu’s Attack Technique increases by 15% while either twin is on court; cannot be blocked",
    "Classmates":{"Suna SSR":"Quick Attack +5/7/9/12/15, Quick Attack +1/2/3/4/5%","Osamu UR":"Block +5/7/9/12/15, Block +1/2/3/4/5%"},
    "Inarizaki's Middle Blockers":{"Suna SSR":"Block +5/7/9/12/15, Block +1/2/3/4/5%", "Omimi SR":"Block +5/7/9/12/15, Block +1/2/3/4/5%"},
    "Third Year from Inarizaki": {"Kita SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Ojiro SSR": "Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%","Akagi SSR": "Cover +5/7/9/12/15, Cover +1/2/3/4/5%","Omimi SR": "Block +5/7/9/12/15, Block +1/2/3/4/5%"},
    "Inarizaki 2nd Years": {"Suna SSR": "Quick Spike +5/7/9/12/15, Quick Spike +1/2/3/4/5%","Ginjima SSR": "Power Spike +5/7/9/12/15, Power Spike +1/2/3/4/5%","Osamu UR": "Quick Spike +5/7/9/12/15, Quick Spike +1/2/3/4/5%","Atsumu UR":"","Kosaku R":""},
    //"Japan Youth Training Camp Teammates":{"Kageyama UR": "","Atsumu UR": "Toss +5/7/9/12/15, Toss +1/2/3/4/5%","Sakusa UR": "Strong Spike +5/7/9/12/15, Strong Spike +1/2/3/4/5%","Komori UR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Hoshiumi UR": "Strong Spike +5/7/9/12/15, Strong Spike +1/2/3/4/5%"},
    "Inarizaki WS Teammates": {"Kita SSR": "Cover +5/7/9/12/15, Cover +1/2/3/4/5%","Ojiro SSR": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%","Ginjima SSR": "Receive +5/7/9/12/15, Receive +1/2/3/4/5%","Kosaku R": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%","Riseki R": "Serve +5/7/9/12/15, Serve +1/2/3/4/5%"},


    //kamomedai
    "Little Giants":{ "Hoshiumi UR": "Power Attack +5/7/9/12/15, Power Attack +1/2/3/4/5%", "Hinata SSR": "" },
    "Friends from Junior High":"Increases Hoshiumi's main stats by 6/7/8/9/10% and increases the [Block] of front row allies by 6/7/8/9/10%. At the start of the match, Hoshiumi gains 1 stack of [All-Rounder] and Hirugami gains 1 stack of [Strong Block].",

    "Top Spiker and Top-Class Libero": "Sakusa’s [Spike] increases by 10%, and Komori’s [Receive] increases by 10%. All allies’ [Receive] power increases by 20% of their [Receive] stat.",

};

//Lowkey just have to remeber that when a bond is create I put it here
//template: "": { category: "school| stats|deployement", activation: { scope: "starters|any", min:  } },
const synergyMeta = {
    "Karasuno": { category: "school", activation: { scope: "starters", min: 4 } },
    "Shiratorizawa": { category: "school", activation: { scope: "starters", min: 4 } },
    "Aoba Johsai": { category: "school", activation: { scope: "starters", min: 4 } },
    "Nekoma": { category: "school", activation: { scope: "starters", min: 4 } },
    "Date Kogyo": { category: "school", activation: { scope: "starters", min: 4 } },
    "Fukurodani": { category: "school", activation: { scope: "starters", min: 4 } },
    "Johsenji": { category: "school", activation: { scope: "starters", min: 4 } },
    "Inarizaki": { category: "school", activation: { scope: "starters", min: 4 } },

    "Karasuno\'s Pillar": { category: "deployment", activation: { scope: "any", min: 2 } },
    "Flexible Aces": { category: "stats", activation: { scope: "any", min: 2 } },
    "Worthy Rival": { category: "stats", activation: { scope: "any", min: 2 } },
    "Kiyoko\'s Knights": { category: "deployment", activation: { scope: "any", min: 2 } },
    "karasuno Senior Year": { category: "deployment", activation: { scope: "any", min: 3 } },
    "\"Guardian Deity\" and \"Wing Spiker\"": { category: "deployment", activation: { scope: "any", min: 2 } },
    "\"Shield\" and \"Spear\" (practice)": { category: "deployment", activation: { scope: "any", min: 2 } },
    "TOMODACHI(Friends!)": { category: "stats", activation: { scope: "any", min: 2 } },
    "Cannon \& Iron Wall": { category: "stats", activation: { scope: "any", min: 2 } },
    "Karasuno\'s sophomore": { category: "stats", activation: { scope: "any", min: 3 } },
    "\"Guardian Deity\" and \"Ace\"": { category: "deployment", activation: { scope: "any", min: 2 } },
    "Leaders Cut from the Same Cloth": { category: "stats", activation: { scope: "any", min: 2 } },
    "Surprising Friendship": { category: "stats", activation: { scope: "any", min: 2 } },
    "Karasuno\'s Wing Spiker": { category: "stats", activation: { scope: "any", min: 3 } },
    "Teammates on the Court": { category: "deployment", activation: { scope: "any", min: 2 } },
    "Simulated Junior Training Teamate": { category: "stats", activation: { scope: "any", min: 2 } },
    "Karasuno\'s Pillar(practice)": { category: "stats", activation: { scope: "any", min: 2 } },
    "\"Shield\" and \"Spear\"(practice)": { category: "deployment", activation: { scope: "any", min: 2 } },
    "Formidable Opponent": { category: "stats", activation: { scope: "any", min: 2 } },
    "Bench cheer": { category: "stats", activation: { scope: "any", min: 2 } },
    "The Returning Trio": { category: "stats", activation: { scope: "any", min: 3 } },
    "\"Sun\" and \"Moon\"": { category: "stats", activation: { scope: "any", min: 2 } },
    "Building Team Chemistry": { category: "stats", activation: { scope: "any", min: 2 } },
    "Karasuno\'s Sophomore(practice)": { category: "deployment", activation: { scope: "any", min: 3 } },
    "Rival Friends": { category: "stats", activation: { scope: "any", min: 2 } },
    "Behind the Smile": { category: "stats", activation: { scope: "any", min: 2 } },
    "Master and Apprentice": { category: "stats", activation: { scope: "any", min: 1 } },
    "Team's Guardians": { category: "stats", activation: { scope: "any", min: 2 } },


    "Aoba Johsai's Sophomore": { category: "stats", activation: { scope: "any", min: 3 } },
    "Blunt and Composed": { category: "deployment", activation: { scope: "any", min: 2 } },
    "The Wolf Pack": { category: "deployment", activation: { scope: "any", min: 2 } },
    "Hidden Fire": { category: "stats", activation: { scope: "any", min: 2 } },
    "Seijoh\'s Senior Year Pillars": { category: "deployment", activation: { scope: "any", min: 2 } },
    "The Wolf Pack(Practice)": { category: "deployment", activation: { scope: "any", min: 2 } },
    "Team Chemistry": { category: "deployment", activation: { scope: "any", min: 2 } },
    "To Greater Heights": { category: "stats", activation: { scope: "any", min: 2 } },
    "Breath of Aoba": { category: "deployment", activation: { scope: "any", min: 2 } },
    "Merciless Trust": { category: "stats", activation: { scope: "any", min: 2 } },
    "Fated Rivals": { category: "stats", activation: { scope: "any", min: 2 } },


    "Nekoma\'s Junior": { category: "stats", activation: { scope: "any", min: 3 } },
    "\"Brain\" and \"Control Tower\"": { category: "deployment", activation: { scope: "any", min: 2 } },
    "Nekoma\'s Wing Spiker": { category: "deployment", activation: { scope: "any", min: 3 } },
    "Grit and Competitive": { category: "stats", activation: { scope: "any", min: 2 } },
    "One-on-One Training": { category: "stats", activation: { scope: "any", min: 2 } },
    "The \"Enigmatic\" Teammate": { category: "stats", activation: { scope: "any", min: 2 } },
    "\"Pivot\" and \"Defensive Pivot\"": { category: "stats", activation: { scope: "any", min: 2 } },
    "\"Pivot\" and \"Control Tower\"": { category: "deployment", activation: { scope: "any", min: 2 } },
    "Reliable Seniors": { category: "stats", activation: { scope: "any", min: 3 } },
    "Protective Guidance": { category: "deployment", activation: { scope: "any", min: 2 } },


    "Date Kogyo\'s Captains": { category: "stats", activation: { scope: "any", min: 2 } },
    "The Silent and the Snarky": { category: "deployment", activation: { scope: "any", min: 2 } },
    "New Captain \& Tall Rookie": { category: "deployment", activation: { scope: "any", min: 2 } },
    "Date Kogyo\'s Wing Spiker": { category: "deployment", activation: { scope: "any", min: 2 } },
    "Date Kogyo\'s Setter": { category: "stats", activation: { scope: "any", min: 2 } },
    "Date Kogyo\'s Junior": { category: "stats", activation: { scope: "any", min: 2 } },
    "Date Kogyo\'s Senior": { category: "deployment", activation: { scope: "any", min: 3 } },

    "Lifelong Best Friends": { category: "deployment", activation: { scope: "any", min: 2 } },
    "Promising Senpai": { category: "stats", activation: { scope: "any", min: 2 } },
    "Undisputed Aces": { category: "stats", activation: { scope: "any", min: 2 } },
    "Shiratorizawa\'s Middke Blocker": { category: "deployment", activation: { scope: "any", min: 2 } },
    "Prediction VS System": { category: "stats", activation: { scope: "any", min: 2 } },
    "Ushiwaka and Benkei": { category: "stats", activation: { scope: "any", min: 2 } },
    "The Absolute King and the Steadfast Setter": { category: "deployment", activation: { scope: "any", min: 2 } },
    "Shiratorizawa 2nd Years": { category: "stats", activation: { scope: "any", min: 2 } },
    "Shiratorizawa's WS": { category: "deployment", activation: { scope: "any", min: 2 } },
    "Shiratorizawa's Senior": { category: "stats", activation: { scope: "any", min: 5 } },
    "Undisputed Ace and Shadow Setter": { category: "deployment", activation: { scope: "any", min: 5 } },
    "Contrasting Setters": { category: "stats", activation: { scope: "any", min: 2 } },


    "Top Disciple": { category: "stats", activation: { scope: "any", min: 2 } },
    "The Moment you'll be hooked on volleyball":{ category: "stats", activation: { scope: "any", min: 2 } },
    "Fukurodani's Wing Spiker": { category: "stats", activation: { scope: "any", min: 2 } },
    "Fukurodani MBs":{ category: "stats",activation: { scope: "any", min: 2 } },
    "Fukurodani 3rd Years":{ category: "stats",activation: { scope: "any", min: 2 } },
    "Miracle Ace and Attentive Setter": { category: "deployment", activation: { scope: "any", min: 2 } },
    "Tokyo Camp Training Partners": { category: "stats", activation: { scope: "any", min: 4 } },

    "The Value of the 'Stage'":                     { category: "stats",      activation: { scope: "any", min: 2 } },
    "Two High-Energy Guys":                         { category: "stats",      activation: { scope: "any", min: 2 } },
    "Jouzenji's WS":                                { category: "stats",      activation: { scope: "any", min: 2 } },
    "Head and Core":                                { category: "deployment", activation: { scope: "any", min: 3 } },
    "Youth Camp Setters":                           { category: "stats",      activation: { scope: "any", min: 2 } },
    "Strongest High School Twins":                  { category: "deployment", activation: { scope: "any", min: 2 } },
    "Classmates":                                   { category: "stats",      activation: { scope: "any", min: 2 } },
    "Friends from Volleyball Class":                { category: "stats",      activation: { scope: "any", min: 3 } },
    "Inarizaki's Middle Blockers":                  { category: "stats",      activation: { scope: "any", min: 2 } },
    "Third Year from Inarizaki":                    { category: "stats",      activation: { scope: "any", min: 4 } },
    "Inarizaki 2nd Years":                          { category: "stats",      activation: { scope: "any", min: 5 } },
    "Japan Youth Training Camp Teammates":          { category: "stats",      activation: { scope: "any", min: 5 } },
    "Inarizaki WS Teammates":                       { category: "stats",      activation: { scope: "any", min: 5 } },


    "Little Giants":                                { category: "stats",      activation: { scope: "any", min: 2 } },
    "Friends from Junior High":                     { category: "deployment", activation: { scope: "any", min: 2 } },

    "Top Spiker and Top-Class Libero":              { category: "deployment", activation: { scope: "any", min: 2 } },
};

//put what player create the bond
const synergyPairs = {
    "Karasuno\'s Pillar": [["Chikara", "Daichi"]],
    "Flexible Aces": [["Hinata", "Lev"]],
    "Worthy Rival": [["Hinata", "Inuoka"]],
    "Kiyoko\'s Knights": [["Tanaka", "Nishinoya"]],
    "karasuno Senior Year": [["Daichi", "Sugawara", "Asahi"]],
    "\"Guardian Deity\" and \"Wing Spiker\"": [["Nishinoya", "Asahi"]],
    "\"Shield\" and \"Spear\"": [["Tsukishima", "Tadashi"]],
    "TOMODACHI(Friends!)": [["Tanaka", "Yamamoto"]],
    "Cannon \& Iron Wall": [["Asahi", "Aone"]],
    "Karasuno\'s sophomore": [["Tanaka", "Nishinoya", "Chikara"]],
    "\"Guardian Deity\" and \"Ace\"": [["Nishinoya", "Asahi"]],
    "Leaders Cut from the Same Cloth": [["Daichi", "Kuroo"]],
    "Surprising Friendship": [["Aone", "Hinata"]],
    "Karasuno\'s Wing Spiker": [["Tanaka", "Asahi", "Chikara"]],//verify this one later on since 3 Wspikers
    "Teammates on the Court": [["Hinata", "Kageyama"]],
    "Simulated Junior Training Teamate": [["Kanji", "Tsukishima"]],
    "Karasuno\'s Pillar(practice)": [["Chikara R", "Daichi SR"]],
    "\"Shield\" and \"Spear\"(practice)": [["Tsukishima SR", "Tadashi R"]],
    "Formidable Opponent": [["Nishinoya", "Yaku"]],
    "Bench cheer": [["Hisashi", "Kazuhito"]],
    "The Returning Trio": [["Hisashi", "Kazuhito", "Chikara"]],
    "\"Sun\" and \"Moon\"": [["Tsukishima", "Hinata"]],
    "Building Team Chemistry": [["Tanaka", "Kageyama"]],
    "Karasuno\'s Sophomore(practice)": [["Tanaka SR", "Nishinoya SR", "Chikara R"]],
    "Rival Friends": [["Kenma", "Hinata"]],
    "Behind the Smile": [["Daichi", "Kuroo"]],
    "Master and Apprentice": [["Tsukishima", "Kuroo"]],
    "Team's Guardians": [["Nishinoya", "Yaku"]],

    "Aoba Johsai's Sophomore": [["Watari", "Yahaba", "Kentaro"]],
    "Blunt and Composed": [["Kindaichi", "Kunimi"]],
    "The Wolf Pack": [["Kindaichi", "Kunimi"]],
    "Hidden Fire": [["Kentaro", "Yahaba"]],
    "Seijoh\'s Senior Year Pillars": [["Matsukawa", "Hanamaki"]],
    "The Wolf Pack(Practice)": [["Iwaizumi", "Kentaro"]],
    "Team Chemistry": [["Oikawa", "Iwaizumi"]],
    "To Greater Heights": [["Oikawa", "Kindaichi"]],
    "Breath of Aoba": [["Iwaizumi", "Oikawa"]],
    "Merciless Trust": [["Oikawa", "Kentaro"]],
    "Fated Rivals": [["Oikawa", "Ushijima"]],

    "Nekoma\'s Junior": [["Teshiro", "Inuoka", "Lev"]],
    "\"Brain\" and \"Control Tower\"": [["Kenma", "Kuroo"]],
    "Nekoma\'s Wing Spiker": [["Ifukunaga", "Kai", "Yamamoto"]],
    "Grit and Competitive": [["Kenma", "Yamamoto"]],
    "One-on-One Training": [["Lev", "Yaku"]],
    "The \"Enigmatic\" Teammate": [["Kenma", "Lev"]],
    "\"Pivot\" and \"Defensive Pivot\"": [["Kenma", "Yaku"]],
    "\"Pivot\" and \"Control Tower\"": [["Kenma", "Kuroo"]],
    "Reliable Seniors": [["Kuroo", "Yaku", "Kai"]],


    "Date Kogyo\'s Captains": [["Kenji", "Kaname"]],
    "The Silent and the Snarky": [["Aone", "Kenji"]],
    "New Captain \& Tall Rookie": [["Kenji", "Kanji"]],
    "Date Kogyo\'s Wing Spiker": [["Yutaka", "Takehito"]],
    "Date Kogyo\'s Setter": [["Kanji", "Kaname"]],
    "Date Kogyo\'s Junior": [["Jingo", "Sakunami"]],
    "Date Kogyo\'s Senior": [["Takehito", " Kaname", "Kamasaki"]],

    "Ushiwaka and Benkei": [["Ushijima", "Ohira Shion"]],
    "The Absolute King and the Steadfast Setter": [["Shirabu", "Ushijima"]],
    "Shiratorizawa 2nd Years": [["Shirabu", "Kawanishi"]],
    "Shiratorizawa's WS": [["Ohira", "Goshiki"]],
    "Shiratorizawa's Senior": [["Yamagata", "Ohira", "Semi", "Tendo", "Ushijima"]],
    "Undisputed Ace and Shadow Setter": [["Ushijima", "Shirabu"]],
    "Contrasting Setters": [["Shirabu", "Semi"]],


    "Top Disciple": [["Bokuto", "Hinata"]],
    "The Moment you'll be hooked on volleyball": [["Bokuto", "Tsukishima"]],
    "Fukurodani's Wing Spiker": [["Bokuto", "Sarukui"]],
    "Fukurodani MBs":[["Onaga","Washio"]],
    "Fukurodani 3rd Years": [["Bokuto", "Komi", "Konoha", "Sarukui", "Washio"]],
    "Miracle Ace and Attentive Setter": [["Bokuto", "Akaashi"]],
    "Tokyo Camp Training Partners": [["Bokuto", "Kuroo", "Akaashi", "Tsukishima"]],

    "Head and Core":[["Kita","Atsumu","Osamu"]],
    "Strongest High School Twins":[["Atsumu","Osamu"]],
    "Classmates":[["Suna","Osamu"]],
    "Friends from Volleyball Class":[["Atsumu","Osamu","Ojiro"]],
    "Inarizaki's Middle Blockers":[["Suna","Omimi"]],
    "Third Year from Inarizaki":[["Kita","Akagi","Ojiro","Omimi"]],
    "Inarizaki 2nd Years":[["Suna","Kosaku","Atsumu","Osamu","Ginjuma"]],
    "Inarizaki WS Teammates":[["Kita","Ojiro","Ginjima","Kosaku","Riseki"]],

    "Little Giants": [["Hoshiumi", "Hinata"]],
    "Friends from Junior High": [["Hoshiumi", "Hirugami"]],

    "Top Spiker and Top-Class Libero":[["Komori","Sakusa"]],
};

window.characters = characters;
window.synergyDescriptions = synergyDescriptions;
window.synergyMeta = synergyMeta;
window.synergyPairs = synergyPairs;